### ISSUE TITLE
[BUG]  I have a DLSS Swapper watermark on the bottom left of my screen in games 

### ISSUE THREAD

**Issue by Zodiac0112** [beeradmoore/dlss-swapper#100]
I have a watermark telling me what version is used and what resolution is being upscaled to and from. I have no idea how this popped up or why, but so far have only seen it in Horizon Zero Dawn. How do I get rid of it, I can't find anything about it anywhere.

I only put this here in case it's a bug, I'm not sure if it's intended on some games, or if I did something to cause it to pop up, but it wasn't there initially, it popped up after a while, I'm thinking maybe I pressed something.

It won't let me paste a screenshot.

**Comment by beeradmoore** [comment]
DLSS Swapper does not have any overlay, nor do we inject anything into the DLSS dlls we provide (TBH I wouldn't even know where to start if we did want to do that 😂)

Is it only appear in games? 

It sounds like Windows derped and left an icon on the screen after a start menu/desktop shortcut/taskbar was last displayed. I'd try a reboot and see if that fixes it.

**Comment by Zodiac0112** [comment]
It won't let me add a PNG/JPG here, I'm guessing there's another way to drop screenshots here. I can show you exactly what it is

**Comment by beeradmoore** [comment]
You should be able to drag and drop into the text area and it should upload the image for you.

**Comment by Zodiac0112** [comment]
It's just have errors processing the file. I'm new to GitHub comments and posting as you can probably tell

**Comment by beeradmoore** [comment]
That is odd and unfortunate. Have you tried restarting your computer to see if the icon goes away? 

If you still want to share the picture are you able to Tweet it at DLSS Swapper on [Twitter](https://twitter.com/dlss_swapper), or post it in a thread on the [Reddit](https://www.reddit.com/r/DLSS_Swapper/)?

**Comment by Zodiac0112** [comment]
Okay, I tweeted it at DLSS Swapper, turns out it's more than just Horizon Zero Dawn

**Comment by beeradmoore** [comment]
For anyone wondering what this overlay looked like [here](https://twitter.com/MrZodiac011/status/1602863605723955201) is the Twitter thread.

**Comment by beeradmoore** [comment]
Final resolution was the registry option for `
HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\Global\NGXCore\ShowDlssIndicator` was enabled somehow. Setting this to 0 fixes it.
