### ISSUE TITLE
Encrypted XBox Apps

### ISSUE THREAD

**Issue by PrincessAkira** [beeradmoore/dlss-swapper#101]
How would you target these Apps?
![image](https://user-images.githubusercontent.com/45071533/207916707-dc01f8a1-bd35-4755-b15d-3770179cc3e9.png)
XBOX App. FH5 in this case

**Comment by beeradmoore** [comment]
Support for games installed via Xbox App has been added for a while. However you can't do that to apps installed directly in WindowsApps folder. If you installed with the [advanced Xbox apps installer thing](https://www.xda-developers.com/xbox-app-preview-pc-advanced-install-features/) then the game will be installed in a custom folder.

DLSS Swapper will only detect these type of games and not any games installed in WindowsApps folder (though technically they are, they are just linked externally)

When you attempt to swap it may tell you that you need to run as administrator to do this.
