### ISSUE TITLE
No GoG.com games detection?

### ISSUE THREAD

**Issue by Celinna1** [beeradmoore/dlss-swapper#102]
as ist seems the program doesnt detect gog games installed by gog galaxy.

no Cyberpunk2077 and no Witcher 3 Next-Gen both installed by gog. Both have DLSS

**Comment by beeradmoore** [comment]
GoG support was added. Are you using an updated version of DLSS Swapper?

If you go into the app settings there should be an option to toggle on and off each platform. If you don't see this you may need to update.

**Comment by Celinna1** [comment]
> GoG support was added. Are you using an updated version of DLSS Swapper?
> 
> If you go into the app settings there should be an option to toggle on and off each platform. If you don't see this you may need to update.

oh youre right had the Windows Store Version, wasnt updated... my fault :)
