### ISSUE TITLE
[BUG] Unable to install

### ISSUE THREAD

**Issue by Snazzie** [beeradmoore/dlss-swapper#111]
**Describe the bug**
Unable to install dlss swapper

**To Reproduce**
running the msix bundle from releases

**Expected behavior**
it allows us to install

**Screenshots**
![image](https://user-images.githubusercontent.com/19627023/217525031-1d27b27a-8cb3-4684-a47b-94b9893f6fc3.png)

**Additional context**

**Comment by beeradmoore** [comment]
Also 1.0 pre-release is out that doesn't require those certificates.

https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0
