### ISSUE TITLE
[BUG] Unable to install

### ISSUE THREAD

**Issue by ggfsae578** [beeradmoore/dlss-swapper#112]
**Describe the bug**
I try to open the dlss installer (I did the signing ticket and its on my desktop) and the install button is greyed out.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beeradmoore** [comment]
I think you possibly didn't install the dependencies.

But that is ok because with the [1.0 pre-release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.0.0) you don't need any of that. Can you give 1.0 a go and see if that works?

**Comment by beeradmoore** [comment]
Closing as there was no reply in 3 weeks.
