### ISSUE TITLE
"The specified file could not be encrypted"

### ISSUE THREAD

**Issue by metroidmen** [beeradmoore/dlss-swapper#113]
Whenever I try to use the swap command I get an error and in the log it says "The specified file could not be encrypted" and then the game disappears from the DLSS Swapper games list.

Not sure what is going on here, I appreciate the help!

**Comment by beeradmoore** [comment]
Hey @metroidmen , if you go to the settings icon there should be a section about the error logs. If you could make this error happen again and then grab the latest error log and attach it below.

Does it only happen to specific platforms, eg. games only from Steam, games only from GoG?

Currently unsure where this error is coming from as we don't encrypt/decrypt anything.

**Comment by metroidmen** [comment]
> Hey @metroidmen , if you go to the settings icon there should be a section about the error logs. If you could make this error happen again and then grab the latest error log and attach it below.
> 
> Does it only happen to specific platforms, eg. games only from Steam, games only from GoG?
> 
> Currently unsure where this error is coming from as we don't encrypt/decrypt anything.

Thank you for your response! I just opened the application and was prompted for the new update. After updating, the error no longer appears. I do, however still have that previous log file with the errors in it. I will attach it. This was happening with all games, regardless of platform. 
[dlss_swapper_20230210.log](https://github.com/beeradmoore/dlss-swapper/files/10717516/dlss_swapper_20230210.log)

**Comment by beeradmoore** [comment]
Glad an update fixed it. The new version (v1.0) runs as a different type of program so maybe that is why updating fixed it.

Do you happen to have any form of drive encryption on, like BitLocker or something?

**Comment by metroidmen** [comment]
> Glad an update fixed it. The new version (v1.0) runs as a different type of program so maybe that is why updating fixed it.
> 
> Do you happen to have any form of drive encryption on, like BitLocker or something?

Not at all. Interestingly enough, I had this working without issue, then I had to do a clean install of Windows. After doing so, I reinstalled DLSS Swapper and that’s when the issue began. Super weird that it worked before the clean install.

**Comment by beeradmoore** [comment]
Indeed. 

Closing this issue as its now resolved.
