### ISSUE TITLE
[BUG] Could not export DLSS dll.

### ISSUE THREAD

**Issue by hb0nes** [beeradmoore/dlss-swapper#114]
**Describe the bug**
Could not export DLSS dll.

**To Reproduce**
Download and install DLSS, download latest (2.5.1).

**Expected behavior**
A successful download.

**Screenshots**
![image](https://user-images.githubusercontent.com/38855893/218327286-1cb9249e-cf50-41e2-ab7e-c8cfe72d3b0e.png)
![image](https://user-images.githubusercontent.com/38855893/218327291-c95aba02-90ed-4411-b526-b8d6fedef497.png)

**Additional context**
Windows 11. Installed program. Tried portable as well, by Running as Administrator.

Found the logfile:
```
2023-02-12 18:39:34.318 +01:00 [ERR] FileVersionInfoExtensions.cs:24 GetMD5Hash - C:\Program Files (x86)\Steam\steamapps\common\Hogwarts Legacy\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll, The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Hogwarts Legacy\Engine\Plugins\Runtime\Nvidia\DLSS\Binaries\ThirdParty\Win64\nvngx_dlss.dll' because it is being used by another process.
```
The game is not currently running.

**Comment by hb0nes** [comment]
Uninstalled and manually downloaded DLSS from techpowerup.com to replace the game's DLSS.
Not sure if this is a bug in this program. Closing.

**Comment by beeradmoore** [comment]
Thanks for the error log. As far as I can tell it isn't related to a bug with us, but without checking into it with process explorer it would be hard to know what is keeping the DLL open.

Happy you got a work around though.

**Comment by hb0nes** [comment]
Yeah I used Windows PowerToys to find out if there were any processes
keeping a handle on it but it came up empty.
That's when I decided to just drop in the DLSS dll manually and close the
issue.

Seemed like a Windows thing :).

Op zo 12 feb. 2023 om 23:25 schreef Brad ***@***.***>:

**Comment by beeradmoore** [comment]
Dang Windows.

All good. I'll keep an ear out for if we hear of similar things happening. 

I also did not know PowerToys could do that, will have a tinker with that later.

**Comment by KittySkin** [comment]
On my end, downloading a from the library result in the same situation, I can't export. I face the same error, even when I just want to export the file, not installing it into any game.
Where can I found the logfile to add more information?

**Comment by beeradmoore** [comment]
In the settings screen there is an option to change how loud the logs are, below that there is a link to the current log.
