### ISSUE TITLE
[Feature request] Also support Frame Generation DLSS (DLSS 3)

### ISSUE THREAD

**Issue by Thortok** [beeradmoore/dlss-swapper#116]
It would be great if you could also support upgrading/swapping for DLSS 3 file as well:

https://www.techpowerup.com/download/nvidia-dlss-3-frame-generation-dll/

**Comment by beeradmoore** [comment]
Here's hoping! Glad it had done interest.

Closing this issue for now in favour of #85 where we are tracking updates. If you want to be notified of anything about DLSS 3 I'd go over there and hit subscribe. If not hopefully you see it in an update soon.
