### ISSUE TITLE
[Feature request] Filter only DLSS supported games

### ISSUE THREAD

**Issue by someONEgood** [beeradmoore/dlss-swapper#12]
**Is your feature request related to a problem? Please describe.**
Not specifically a problem, just a design choice/preference. Really appreciate that you took the time to create this.

**Describe the solution you'd like**
The option to filter out non-DLSS supported games, rather than display the entire Steam Library.
Preferably this would just scan the system for the relevant .exe's _(or whatever method of DLSS detection you're using, probably nvngx_dlss.dll?)_ of supported games with no need for specific launcher support. _(Steam, Epic, Rockstar Launcher, GOG, etc)_
If new titles are released that support DLSS, the community could add the relevant .exe to search for via github.

**Describe alternatives you've considered**
Alternatively, scan titles at startup for the "DLSS was not detected in <insert Title here>." prompt, and then hide those titles accordingly. Folk could opt-in to this method or not at first startup, or via additional prompt if already installed.

**Additional context**
Just a side note, perhaps add to the "Please note" section of the Readme:

This tool does not allow DLSS 1.0 supported games to work with DLSS 2.x+ DLL's.
These games need 2.0 implementation by their respective developers and updating their .dll may result in your game not working properly. These include titles such as Battlefield V, Shadow of the Tomb Raider, etc.

See this list for compatible titles: https://en.wikipedia.org/wiki/List_of_games_with_support_for_high-fidelity_image_upscaling

**Again thank you for this great utility.**

**Comment by beeradmoore** [comment]
I can see two enhancements coming out of this which I think could solve all your problems.

1. In the games list view, add a filter button. Within that filter add a checkbox for "Hide games without DLSS", and as a bonus a second bunch of check boxes so users can have the tool only scan Steam and not Epic Game Store (maybe they only use Unreal Engine from Epic and not nay games so they don't care for it scanning it).

2. If a game has DLSS 1.X, don't show any 2.X dlls, likewise if a game has 2.X, don't show any 1.X dlls as an option. That way we can keep those seperate.

What do you think if we did that?

**Comment by CuddleBear92** [comment]
Couldnt the client be pre-filled with SteamDB info for example out of the box? https://steamdb.info/tech/SDK/NVIDIA_DLSS/

Already lists all the titles and ID's on Steam with the titles in question. sadly no mention of what version anything is sadly.
But if you login to SteamDB then you could easily pull the hash value of the dlss dll files and map it all that way. 
Makes sense to work out a base that way atleast.

**Comment by beeradmoore** [comment]
Main problem with that is SteamDB is only useful for Steam games. It's easier for the client to know that a user has Steam, Origin, and Epic Game Store installed, and then detect their games directory as: 
C:\Steam\games\
E:\Origin\games_dir\
F:\EpicGameStore\the_games\
and then it can search those directories for the DLSS dll which is always named nvngx_dlss.dll (at least as far as I know its always named that).

The tricky bit is knowing, how does Epic Game Store client installed on someones PC know where it itself stored games. I've done some research on EGS that you can read [here](https://github.com/beeradmoore/dlss-swapper/issues/11#issuecomment-904187322). I have not looked into the other platforms yet.

As for that link, that is awesome to know it exists!. Thanks for sharing! While it may not be directly useful to DLSS Swapper, it does give me a giant list of games that support DLSS, a bunch of those games potentially exist on other platforms which gives me more test data to inspect those game libraries with.

**Comment by CuddleBear92** [comment]
While SteamDB doesn't directly help EGS and Origin and the others. In-directly it can as most titles drop on Steam anyway. 
You could automate tracking of updates for the titles already logged to have DLSS and allow it to check and compare the dll hash value on each update to spot any changes. this way you can easily see what titles gets what updates or even custom versions. 
having it all be hash based in its logging and mapping makes sense in the end. 

And all the mapped data could be re-used for any other client or usecase. 

Another way to do it would be to just have the mapped hashes in the client and let each client do a SHA1 calculation of each dll file it finds in the supported titles. If its not a known hash then it could report it to you for pushing an update to the rest of the clients. 
But maybe i am thinking about this in a larger manner. 

Just having the hash values dictate what version it is and everything else makes the most sense compared checking and comparing the version of the file itself. 

Also to note, that install registries can fail and can mess up for sure and can be incorrect or missing.

**Comment by ZeMilkmann** [comment]
Regarding the rating system: You could simply have users agree to send back which versions they use for which game (if changed from default) as a very rudimentary "XX% of people who changed DLSS on game Y are using version Z".

This makes review bombing much harder because it's much mess likely that someone will run 100 real or virtual machines just to mess with the results of a non-profit without being able to gain anything. 

You could also add fingerprinting like anti-cheat tools do, but that may be a bit of a nightmare regarding GDPR

**Comment by beeradmoore** [comment]
Doesn't take VMs to ruin the system, if it's just a web request you can add a loop in there that goes over 100 times. 

But what if it sends machine ID? Well then in each request I (as the bad person) would just generate a new ID.

I think it'd have to be handled on the server side trying to fingerprint legitimate users, and then later analysing the data and realising "woah all these results are fake".

Not out of the world of impossible to do, also it defends against something that is not likely to happen. So risk/reward is all there.

**Comment by beeradmoore** [comment]
Also keep in mind, it's a free tool. As soon as there is an online component it starts costing me money.  Sponsorship/donations is great and all, but when it can't be a full time job to be ready and quickly fix things when they break people are going to be mad that they used money on something that doesn't work.

**Comment by beeradmoore** [comment]
Current progress of the filter.

![Screenshot 2021-09-06 091404](https://user-images.githubusercontent.com/904737/132144297-0a346b23-ce58-4092-8fc5-bf03ba227bc3.png)

**Comment by beeradmoore** [comment]
This has since been released.
