### ISSUE TITLE
[BUG] Swapping DLSS version from 3.1.1.0 to 3.1.1.0 v2 makes the program crash

### ISSUE THREAD

**Issue by MarcoReckless** [beeradmoore/dlss-swapper#121]
**Describe the bug**
Swapping DLSS version from 3.1.1.0 to 3.1.1.0 v2 makes the program crash, it does not happen when swapping a single game but it happens on the second time I do it.

**To Reproduce**
1. Select any game with 3.1.1.0 v1.
2. Swap it to 3.1.1.0 v2.
3. Repeat step 1 and 2 for another game.

**Expected behavior**
The program doesn't need to crash (obviously) and it should show clearly when the v2 variant is installed.

**Comment by beeradmoore** [comment]
I am unable to replicate this issue. 

Are you using the [latest version](https://github.com/beeradmoore/dlss-swapper/releases) of DLSS Swapper (v1.0)?

**Comment by MarcoReckless** [comment]
> I am unable to replicate this issue.
> 
> Are you using the [latest version](https://github.com/beeradmoore/dlss-swapper/releases) of DLSS Swapper (v1.0)?

I uninstalled it and opted for the portable version, I'm not getting the crashes anymore; still, a UI change for the v2 variant would greatly help.

**Comment by beeradmoore** [comment]
I have filed that UI change in #126 so it does not get lost. Worth while addition, thanks for mentioning it.
