### ISSUE TITLE
[BUG] This certificate has been revoked by its certification authority

### ISSUE THREAD

**Issue by PiFZAR** [beeradmoore/dlss-swapper#123]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/126948941/222886329-40053ac6-3fc9-48d3-ada8-7fb35aeb33b3.png)

**Additional context**

How do you fix this?

**Comment by beeradmoore** [comment]
To fix you can install the latest version that no longer requires certificates. Please read the changelog for relevant information on what the new version means and what you may have to do.

**Comment by PiFZAR** [comment]
> To fix you can install the latest version that no longer requires certificates. Please read the changelog for relevant information on what the new version means and what you may have to do.

Thank you very much, I'm sorry I didn't read so much about it.
