### ISSUE TITLE
[Feature request] Recommended dlss version

### ISSUE THREAD

**Issue by MuhannadYT** [beeradmoore/dlss-swapper#129]
**Is your feature request related to a problem? Please describe.**
It takes some time to test different DLSS versions to see which one works best
**Describe the solution you'd like**
The solution would be something like a voting system, where people will vote on which dlss version works best for said game.
The recommended version could be marked with (Recommended)

**Comment by beeradmoore** [comment]
Hey @MuhannadYT , thanks for the feature request.

This one has come up before but it is rather difficult to do while also not spending a dollar. I am open to ideas if you have some. I'm going to put extra detail into this response so I can link to it in future.

"best" is subjective. Is this best performance, or best with the least amount of artifacting? Lets assume we just think its whatever people enjoy using. Well where to they mark it down? We'd need some sort of online service or our own server for them to submit this info where we can also fetch it from. Easy done.

But now how do we stop people submitting 5 votes for 3.1.1 to try make it the best? Well now we need an login system of some sort. This also adds complexity as now our server has a database. All this costs money. Plus this code itself should be maintained. But let's assume we have that set up.

Now when people vote for a particular DLSS version I assume they are voting for a particular game as well. Certain DLSS versions may be better than others depending on the game. So we need to record the game. Game versions also change so it could be possible that a newer game version performs better with a newer DLSS version (eg. Maybe the game itself was updated with it).

Another thing on top of this possibly to collect Nvidia driver version and the GPU that the person is using. Both of those could impact the decision that user has for if a particular version of DLSS is best.

So now its a lot of data, some user data, data we'd hope is updated by the community all running on servers that someone has to pay for.

So a recommended system would be great, but it gets out of hand very quickly. We can certainly trim some of the above things down to make it easier but it's still a rather large task.

This may not help but we are adding a notes section to the games screen (which currently does not exist) so you can leave your own notes of how certain DLSS versions performed with this game. But that is only a note for yourself, it won't get sent anywhere for others to see.

**Comment by MuhannadYT** [comment]
Thanks for your reply @beeradmoor, tbh you are right different gpus may give different results so it is extremely hard to state a recommend version. While the note system does take more time, it is a lot more stable and the use can test for himself. 

Thank You

**Comment by beeradmoore** [comment]
Thanks for your understanding. Closing this issue for now. Maybe someday it can be a possibility.
