### ISSUE TITLE
Add DLSS-FG on MSFS2020(Microsoft Flight Simulator)

### ISSUE THREAD

**Issue by PHGaming121** [beeradmoore/dlss-swapper#130]
**Is your feature request related to a problem? Please describe.**
i installed dlss 3.1.11 on MSFS2020, but... where is the FG(Frame Generation) on the settings menu

**Describe the solution you'd like**
add frame generations on fs2020 

**Additional context**
im using the Xbox app flight sim

**Comment by beeradmoore** [comment]
Hey, there is some confusion here and I fully understand why.

DLSS v3.1.11 is not DLSS 3 🥲 (thanks nVidia) 

It is DLSS 2 version 3.
DLSS frame generation is a different file doing different things. DLSS FG will be coming to DLSS Swapper in version 1.1.

However, if the game never had DLSS FG we can't magically add it. Just like if the game never had DLSS we can't magically add that either. We can only upgrade what exists.
