### ISSUE TITLE
[Feature request] Detect games that use the upscaler mod by puredark

### ISSUE THREAD

**Issue by DevilzAvacado** [beeradmoore/dlss-swapper#135]
PureDark has [a mod](https://www.nexusmods.com/site/mods/502) that implements up-scaling technology to a couple of bethesda games. it supports fsr, xess and dlss. would there be for this to detect the that mod to install/update the dlss dll like it does with any other game with dlss support?

**Comment by beeradmoore** [comment]
If that mod puts the dlss dll into the game directory with the correct file name it should automatically detect it and allow you to update it.
If the mod does other things and doesn't actually put the dll into the game folder or names it with a non standard name (anything other than nvngx_dlss.dll) then we can't detect the game supports it.

If you use the mod on a game from your steam folder are you able to then search that game folder for nvngx_dlss.dll? And if it is found does using DLSS Swapper then detect it?
