### ISSUE TITLE
[Feature request] Sort games list by platform

### ISSUE THREAD

**Issue by HarryKleins** [beeradmoore/dlss-swapper#137]
Good morning,

Is your feature request related to a problem? Please describe.
Make sure you can sort games by platform. To make it simple to know that the games come from steam, ubisoft, GO etc.

Describe the solution you'd like
added category by game platform

Additional context

Thanks in advance

**Comment by beeradmoore** [comment]
Morning Harry.

From the top right corner of the games list you can change the grouping to group by library. 

Is this what you were after?

**Comment by HarryKleins** [comment]
Thank you very much, I had not found.

Problem solved.

Thanks again :)

**Comment by beeradmoore** [comment]
No worries. Have a great day.
