### ISSUE TITLE
[BUG] MSFS not showing up in the list

### ISSUE THREAD

**Issue by LiNk34725** [beeradmoore/dlss-swapper#140]
Hey, 
MS-store version of MSFS doesn't show up in DLSS Swapper.
Other games from MS Store are showing up (like Redfall), and also from Steam.

Also, when I click on the parameters wheel, nothing happen.

I installed the certificate as required.

**Comment by beeradmoore** [comment]
MSStore version of the app is no longer supported (and no longer available) as MS no longer allows me to send updates for the application because they have a rule saying a MSStore app cannot download executables. DLSS dlls are executables apparently 🤷‍♂️.

If you could [uninstall](https://beeradmoore.github.io/dlss-swapper/uninstall/) (certificate no longer required) and then install from the [releases](https://github.com/beeradmoore/dlss-swapper/releases) page.

Thanks for bringing this up as I need to go review the install instructions and update to the new install system.

**Comment by LiNk34725** [comment]
Hey, thanks for the answer !
I maybe didn't express very well : I'm talking about MicroSoft Flight Simulator (MSFS), not DLSS Swapper on the MS Store :)

I did however install from the release page

**Comment by beeradmoore** [comment]
Ohhh my bad. I should not respond to issues before morning coffee 😅

If you installed via the MSStore we will not be able to detect the game. Even if we could the files we'd be required to swap are likely in the heavily secured WindowsApps folder.

The only way we can detect games and change their files is if:
1. It's installed via Xbox app.
2. Have the [advanced install system](https://www.google.com.au/amp/s/www.ghacks.net/2021/11/20/xbox-pc-app-now-lets-users-in-the-insider-program-to-install-games-in-any-folder-heres-how-to-do-it/%3famp) enabled.
3. Not let it install into WindowsApps folder.

That feature was in insiders builds in 2021, surely it's made its way to general release by now?

I can do a test install of it and confirm I can see it on DLSS Swapper to save you having to uninstall and reinstall only to find it doesn't work. It's a chonky game for sure 😂

**Comment by beeradmoore** [comment]
For me this is what my Xbox app settings looks like regarding installing,
![Screenshot 2023-06-23 062646](https://github.com/beeradmoore/dlss-swapper/assets/904737/589cc0ce-809a-4248-8e68-8ae24099f8b1)

And this is what version I am currently using,
![Screenshot 2023-06-23 062711](https://github.com/beeradmoore/dlss-swapper/assets/904737/03730570-f9ac-4efb-b783-d6b2d44aa6f5)

When I go to install I get this prompt,
![Screenshot 2023-06-23 062956](https://github.com/beeradmoore/dlss-swapper/assets/904737/b68b30c6-b88e-48ee-8922-27a6b9771041)

Games in any of these folders should be detected and DLSS swappable.

I'll update you in a 157gb confirming if it shows or not.

Above I said I need to update the docs for MSFT store, I also should update the docs for this.
Would you be able to confirm for me that your Xbox app settings look similar to this (assuming you are not in a beta build of Xbox app as well)?

**Comment by LiNk34725** [comment]
Ahah no problem !!

It worked !! Thanks a lot !! :)
It looks the same, it asked me the same 157Gb update but only moved 2Gb (I have a weird in-house MSFS install)
All I did is to click on MSFS, "Manage", then "Move"

**Comment by beeradmoore** [comment]
Replied just as I came back to see it worked with the 2gb base install :P 
![Screenshot 2023-06-23 063834](https://github.com/beeradmoore/dlss-swapper/assets/904737/46a615ba-2019-44ea-84a9-d46cb59a79ff)

Handy to know you can move rather than re-install everything. I'll keep that in mind.
