### ISSUE TITLE
[Feature request] Manual Add Games 

### ISSUE THREAD

**Issue by GwnMichael** [beeradmoore/dlss-swapper#141]
Would it be possible to add a feature to manual add games to DLSS tweaker?

Would save a bit off time off going into the game folder and keeping track off the original DLL.

**Comment by beeradmoore** [comment]
Do you mean DLSS Swapper, or another tool DLSS Tweaker?

If you mean to Swapper we have a ticket at #8 that has a few requirements that need to get done first.

If you mean to Tweaker, can you explain more of what it does and how DLSS Swapper would be keeping track of it?

**Comment by GwnMichael** [comment]
DLSS swaper, sorry my fault should have read it again.

That’s great to see! Can’t for the 1.1 release and see it added by then.

Thanks for the hard work, really appreciate it!

**Comment by beeradmoore** [comment]
All good. [DLSSTweaks](https://github.com/emoose/DLSSTweaks) was the other tool I was thinking of. Closing for now. If you want to see updates regarding manually adding games, feel free to head over to #8 and hit subscribe.
