### ISSUE TITLE
[Feature request] Ubisoft Connect support

### ISSUE THREAD

**Issue by beeradmoore** [beeradmoore/dlss-swapper#15]
**Is your feature request related to a problem? Please describe.**
No Ubisoft Connect games appear.

**Describe the solution you'd like**
Add support for scanning of games installed via Ubisoft Connect

**Additional context**
Test games - Watchdogs Legion

**Comment by cftad** [comment]
📓 Some useful implementation info

ℹ️ _Images have yet to be implemented as further investigation is required to get these to work in a sustainable way._

## Registry
1. Check for Ubisoft Connect installed in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ubisoft\Launcher`
2. Game installs are registry keys based on their App ID e.g **635** for Rainbow Six Siege
3. Subkeys evaluated from `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs` and path obtained from `InstallDir` 
4.  Game path evaluated for  `nvngx_dlss.dll`

**Comment by MorGuux** [comment]
https://github.com/JosefNemec/Playnite/tree/c1973fcc94da97c5863215311924e7adeddc291a/source/Plugins/UplayLibrary

Demonstrates how to fetch Ubisoft games, including artworks.

**Comment by beeradmoore** [comment]
This has been added in the [v0.9.12.0 preview](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.12.0). Closing for now, if you have any issues with Ubisoft Connect compatibility please file new issues.
