### ISSUE TITLE
this tool is a joke

### ISSUE THREAD

**Issue by NeverBeLazyG** [beeradmoore/dlss-swapper#152]
after 2 years still no possibility to add custom games. this is a joke. lazy developers. i uninstalled it. it detects 10% of my games.

340MB tool, which is not able to to something what a 1KB powershell tool can do. i wrote my own shell tool, to swap dlss files. it took me half an hour to write that tool.

**Comment by thepwrtank18** [comment]
If you have something, share it with the whole class

**Comment by beeradmoore** [comment]
Don't be one of those lazy devs I hear about, go open source it and share it with the community 🤷‍♂️

**Comment by NeverBeLazyG** [comment]
> Don't be one of those lazy devs I hear about, go open source it and share it with the community 🤷‍♂️

i'm not someone who would presume to make something like this public. and set up a github page for it. if i would do that, i would make the tool reasonable. i wrote my tool just for me. there are some hardcoded paths etc. in it. i also invested only 30 min.

but if i would publish something like this, i would do it reasonable. not like the developers of dlss-swapper. i mean it's really not complicated. select an exe file, then replace the matching .dll. no idea why these people don't do this, if they already release such a tool with such a name. just embarrassing

**Comment by beeradmoore** [comment]
Well your first mistake is replacing an exe with a dll, that will never work bud.

Anyways, best of luck with your hardcoded script that I'm sure really exists just like my girlfriend in Canada does, as does my uncle who works at Nintendo.

**Comment by NeverBeLazyG** [comment]
> Well your first mistake is replacing an exe with a dll, that will never work bud.
> 
> Anyways, best of luck with your hardcoded script that I'm sure really exists just like my girlfriend in Canada does, as does my uncle who works at Nintendo.

ho ho, so funny. if you are trying to be a funny guy. you missed that. you are not funny. you exactly know what i mean with searching an exe. its for adding a game to the library. like in steam, when you add a non-steam game. but you are same pathetic guy, who knows i am right. but i dont care.  maybe your uncle really works at nintendo. as a room cleaner.

**Comment by thepwrtank18** [comment]
your account was created in 2022 and all your contributions are complaining
