### ISSUE TITLE
[Feature request] Add Frame Generation ?

### ISSUE THREAD

**Issue by Snipy44** [beeradmoore/dlss-swapper#154]
Hello do you thinks is possible to add Frame Generation also ?

**Comment by beeradmoore** [comment]
Hey @Snipy44,
The TL;DR; is, it's coming, unsure when.

The longer answer is that we are tracking the issue in #85 
(if you want to follow updates go here and hit the subscribe button on the right) , but we also need #8 to be implemented first for the new DLSS picker to be able to use DLSS FG (And DLSS D, XeSS, FSR, etc ;))

Closing the ticket for now.
