### ISSUE TITLE
[Feature request] Adding Folder Location

### ISSUE THREAD

**Issue by x8009** [beeradmoore/dlss-swapper#155]
**Is your feature request related to a problem? Please describe.**
Why it's not possible to choose specific folder/folders with all my games?
**Describe the solution you'd like**
adding option to add a folder/folders
**Additional context**

**Comment by beeradmoore** [comment]
Hey @x8009 , thanks for the report.

This issue has started being added and is being tracked in #8 . If you wish to stay updated on changes please hit the subscribe button on the right hand side of that other issue.

Closing this ticket for now.
