### ISSUE TITLE
[Feature request] Use custom file directory for DLSS supported Game 

### ISSUE THREAD

**Issue by KoyuKansou** [beeradmoore/dlss-swapper#158]
Hi

I would like to request a feature that allow you to find game and its dlss file directory because few of my games that support DLSS but doesn't show up on the app

**Comment by beeradmoore** [comment]
Hey @KoyuKansou , 
I think you mean to manually add games into DLSS Swapper? This has been planned and progress has started. You can find more information on that in issue #8
