### ISSUE TITLE
Add support for replacing DLL files for DLSS Upscaling, DLSS Frame Generation and DLSS Ray Reconstruction

### ISSUE THREAD

**Issue by Terepin** [beeradmoore/dlss-swapper#162]
All these three DLSS features are using separate DLL files with their own versioning:
1. nvngx_dlss.dll
2. nvngx_dlssd.dll
3. nvngx_dlssg.dll

DLSS Swapper downloads and replaces only DLL for Upscaling, which limits its usefulness.
Can you add support for replacement of other files as well?

Thank you.

**Comment by Terepin** [comment]
Add, not ass. :D Sorry.

**Comment by beeradmoore** [comment]
Do you know if anywhere is hosting the DLSS RR dlls yet? I haven't checked techpowerup.

TL;DR; of it is, it is planned, but it's a lot more work than people realise.

As for this, it will be a part of #85, which is held up by #8, which both are needed to add the more advanced UI to support DLSS FG/RR. Plus I need to go modify the DLSS Archive that we use to host DLSS files.

**Comment by Terepin** [comment]
TechPowerUp indeed has the files for FG: https://www.techpowerup.com/download/nvidia-dlss-3-frame-generation-dll/
No files for RR yet, though.

**Comment by beeradmoore** [comment]
Thanks @Terepin , closing this for now but it is reference from the above linked issue.
