### ISSUE TITLE
Addi support to nvngx_dlssg.dll too

### ISSUE THREAD

**Issue by RedFoxy** [beeradmoore/dlss-swapper#163]
This is a feature request, why don't you add support to upgrade nvngx_dlssg.dll too? 

**Describe the solution you'd like**
nvngx_dlss.dll and nvngx_dlssg.dll are two base dll to next gen of NVidia support, nvngx_dlssg.dll add support to frame generator and other features by nvidia, so upgrade it will add new fix and support, and maybe prevent trobules using different versions of nvngx_dlss.dll and nvngx_dlssg.dll

**Comment by beeradmoore** [comment]
Hey @RedFoxy , this issue has been requested a few times and is being tracked in issue #85. 

This is a good point about incompatibilities with odd versions of DLSS and DLSSG being mixed. 

Closing this issue for now as a duplicate but adding that bit of feedback to the original issue. If you wish to stay up to date when you go to #85 you can hit the subscribe button to get notifications for updates.
