### ISSUE TITLE
[BUG] Witcher 3: Wild Hunt GOTY (new remastered verison) is not detected

### ISSUE THREAD

**Issue by the4anoni** [beeradmoore/dlss-swapper#165]
**Describe the bug**
Witcher 3: Wild Hunt GOTY (new remastered verison) is not detected in DLSS Swapper

**To Reproduce**
1. Install latest version of game from offline GOG installer
2. Try to find it in DLSS Swapper

**Expected behavior**
Game should be there.
**Screenshots**
![image](https://github.com/beeradmoore/dlss-swapper/assets/13403084/014b3e37-4e1d-4b78-ae0b-a33a54f0a953)

**Additional context**

DLSS Swapper v. 1.0.3.1
Witcher 3: Wild Hunt GOTY v. 4.04

**Comment by beeradmoore** [comment]
Hey @the4anoni , I am exteremly sorry for missing this issue you reported.

Are offline installers just games that install anywhere? If you installed one like that does the GoG launcher show it as installed?

**Comment by the4anoni** [comment]
> Hey @the4anoni , I am exteremly sorry for missing this issue you reported.
> 
> Are offline installers just games that install anywhere? If you installed one like that does the GoG launcher show it as installed?
> 
> Are any of the games you listed installed in the same way?

Hi

I don't have GOG Galaxy installed, so I can't check do they show in launcher.

**Comment by beeradmoore** [comment]
No worries. I'll have to check this one out myself.

If I can't find any way to monitor that you'll have to wait for DLSS Swapper v1.1 when you will be able to manually add game folders.

**Comment by beeradmoore** [comment]
Hey @the4anoni , just an update on this. Doing an initial test on a blank virtual machine without GoG Galaxy installed I am able to confirm I can see it in the registry where GoG would normally place things.

I need to do a test with a game that is not by CDPR to ensure it creates similar entries. If that is successfull it should work for all GoG games regardless of GoG Galaxy being installed or not. If not I can at least get installs working for The Witcher 3 GOTY.

**Comment by beeradmoore** [comment]
Hey @the4anoni , DLSS Swapper v1.0.4 is now released and adds support for games from GOG installers (rather than just GOG Galaxy).
