### ISSUE TITLE
error appxpacke Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)

### ISSUE THREAD

**Issue by phamdattt8787** [beeradmoore/dlss-swapper#166]
help me plss

![Capture](https://github.com/beeradmoore/dlss-swapper/assets/148690329/01e79195-de7d-4bb0-aa6b-52a0dfd4a57c)

**Comment by beeradmoore** [comment]
We haven't distributed like that in a long time. You get the latest version from our releases tab, https://github.com/beeradmoore/dlss-swapper/releases
