### ISSUE TITLE
[Info Request] Source of DLLs?

### ISSUE THREAD

**Issue by jwvanderbeck** [beeradmoore/dlss-swapper#167]
Hello,
In the interest of transparency I was trying to determine where this was getting the DLLs from, but I was unable to determine from a cursory look at the source code.  I have not yet installed, and it might become obvious when I do.

Would it be possible to add information to the Readme indicating the source of the DLLs?

**Comment by beeradmoore** [comment]
Hey @jwvanderbeck , dlls are downloaded from a [dlss-archive](https://github.com/beeradmoore/dlss-archive) repository I manage. Previously I'd wait to hear when new DLSS versions are out (via TechPowerUp and Twitter DMs usually) and then either get my own copy of the dll or use TPUs one. 

Lately all dlls are sourced from [DLSS SDK](https://github.com/NVIDIA/DLSS), but DLSS Swapper isn't downloading them directly from there (yet).
