### ISSUE TITLE
[BUG] Swap DLSS for XBOX app games will corrupt game files

### ISSUE THREAD

**Issue by zycboss** [beeradmoore/dlss-swapper#168]
**Describe the bug**
Swap DLSS any version for XBOX app games will cause the game unable to launch anymore.
Some games will give you an error window, some just crash/disappear.
Swap back DLSS to the original version won't fix it;
Verify game files won't fix it;
You have to uninstall the entire game and redownload it again.

**Additional context**
DLSS swapper porperly showed the Xbox library, and did swapped the DLSS version, so no permission issue.
Tested games: [Wo Long: Fallen Dynasty] [A Plague Tale: Requiem] [Wolfenstein: Youngblood]
The same game in Steam version works fine with DLSS swapper.

**Comment by beeradmoore** [comment]
That is interesting and possibly new behaviour. I have been using DLSS Swapper with Xbox apps since the feature launched, although unsure the last time I swapped for an Xbox App game.

I would have said these are in the handful of games that don't support changing any files, but as you said the Steam version works fine. 

Let me do some testing and get back to you.

**Comment by zycboss** [comment]
> That is interesting and possibly new behaviour. I have been using DLSS Swapper with Xbox apps since the feature launched, although unsure the last time I swapped for an Xbox App game.
> 
> I would have said these are in the handful of games that don't support changing any files, but as you said the Steam version works fine.
> 
> Let me do some testing and get back to you.

I have being test this issue for a few more days, but it actually looks like a Xbox App or Windows bug instead of DLSS Swapper.
Since re-install xbox App and other stuffs did not help, I finally clear re-installed Windows, and try DLSS Swapper again, now all the games are launchable after the swap now, so, you know, Microsoft.

**Comment by beeradmoore** [comment]
> so, you know, Microsoft

Sounds about right 😂. I'll close this issue for now, but if it pops up again please let me know and I'll re-open.
