### ISSUE TITLE
[BUG] uninstalling the program deleted all my files.

### ISSUE THREAD

**Issue by SmashingMist27** [beeradmoore/dlss-swapper#169]
uninstalling program deleted all my files. everything is gone, why did it delete everything from my drive???? my save games are gone.

**Comment by SmashingMist27** [comment]
actually fuming rn, literally dont know what to do. why the fuck would it uninstall everything in the drive that THIS program was in??

**Comment by beeradmoore** [comment]
Sorry to hear this happened, you sure DLSS Swapper did it? 

What version of DLSS Swapper did you have installed? Can you explain what drive letter and path it was installed to and what is actually removed when you uninstalled?

**Comment by SmashingMist27** [comment]
i was using [v1.0.3.1](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.3.1) . 
for uninstallation i did: settings>apps>uninstall.
the reason i wanted to uninstall was to fresh install because the installation scattered a bunch of random files in my game files ssd, and if there was going to be cluttered files i wanted them to be somewhere else.

**Comment by beeradmoore** [comment]
And for the install, did you install DLSS Swapper to a non-C drive (like F: drive or something)?

Uninstalling DLSS Swapper won't remove the files it places in game directories, it only should remove the directory you installed it into.

I will try replicate and see if I can make it destroy everything on my drive as well.

**Comment by SmashingMist27** [comment]
installed to Drive E
![Screenshot 2023-11-08 215039](https://github.com/beeradmoore/dlss-swapper/assets/26682735/570f2f6a-d90f-4cc6-ab5d-87e5cc9a4af3)

**Comment by beeradmoore** [comment]
Over the next day or two I'll test `E:/Clients/DLSS Swapper/` and get back to you.

When you did this did it trash the `Clients` directory, or did it clear out `E:` drive completely, or something else?

**Comment by SmashingMist27** [comment]
it emptied the contents of (E:)>Clients>clients(ex:steam,epicgames,ubisoft) folders. nothing was found in recycle bin

**Comment by SmashingMist27** [comment]
would like to mention before i uninstalled i used the dlss swapper and swapped the current dlss's into my games.

**Comment by beeradmoore** [comment]
Thanks for all the info, I'll try to replicate that happening.

Just double checking to cover all bases, but I assume you didn't do anything like install DLSS Swapper and then physically move it to another directory or anything?

**Comment by SmashingMist27** [comment]
did not move to another directory.

**Comment by beeradmoore** [comment]
Hey @SmashingMist27 , I wasn't able to replicate the exact issue but I possibly might know what has happened. 

![clients_1](https://github.com/beeradmoore/dlss-swapper/assets/904737/02782067-879f-4a39-8f5b-75e6488cfccd)
First screen of the installer, wants to install to `C:\Program Files\DLSS Swapper\`

![clients_2](https://github.com/beeradmoore/dlss-swapper/assets/904737/40913b82-ad71-4803-94e3-bfbf46df9d01)
I change this to my `Clients` folder in my `D:` drive. `Clients` folder also has two sub folders already, `A` and `B`.

![clients_3](https://github.com/beeradmoore/dlss-swapper/assets/904737/f4bac93a-5901-47d8-b67e-84f6c164c574)
But now when I go back to the installer it says it wants to install to `D:\Clients\` and not `D:\Clients\DLSS Swapper\`. As far as I know this is standard practice. If this is what happened I don't at all blame you for using it wrong.

![clients_4](https://github.com/beeradmoore/dlss-swapper/assets/904737/5c5602c1-3091-46c4-a8a4-fe587024bf23)
Now when we go to uninstall it wants to uninstall from `D:\Clients\`

![clients_5](https://github.com/beeradmoore/dlss-swapper/assets/904737/69a9bae7-be26-4523-a475-3ae92cf53c3f)
And when I look at the uninstall log it did remove the other folders, as you can see on here `Remove folder: D:\Clients\A\`

Does this look like something that possibly happened?

Looking into the middle bit where the install directory changed, I feel like this is standard how installers work and it's on the end user to create a new folder to put it in. That way you can install it to a folder called `diss-swapper` or `ds` or `that tool for the things`. I double checked and confirmed and this is how Steam works.

![steam_1](https://github.com/beeradmoore/dlss-swapper/assets/904737/cf25680a-833b-4b72-926a-1c4e2f7ecd7b)

![steam_2](https://github.com/beeradmoore/dlss-swapper/assets/904737/4dc21d58-4e12-4a60-96b2-7a41afe6ef91)
In this situation uninstalling Steam would possibly nuke DLSS Swapper.

If you did install to `E:\Clients\DLSS Swapper\` then I am unsure what happened.

If you did install to `E:\Clients\` then I can see ways how the uninstaller can be improved. Its current state is that it removes everything from its install directory. Idea behind this is that it will remove any of its config files that it may have made (although ironically its config files are stored elsewhere and they do not get removed with an uninstall).

I can try change the installer/uninstaller so it creates a log of files it adds and only removes those. This would avoid removing of some files it shouldn't. The downside is there could be some files that get created after the install which would not get uninstalled. While this isn't the perfect solution, I think it is much better than the alternative which is currently in place.

**Comment by SmashingMist27** [comment]
correct, i installed it into E:\Clients\
