### ISSUE TITLE
[BUG] Assassin's Creed Mirage (Ubisoft Connect) is not detected

### ISSUE THREAD

**Issue by Thortok** [beeradmoore/dlss-swapper#170]
**Additional context**
I heard DLSS was added to AC: Mirage, but I don't see it in this tool. It's one of the few non-steam games I have, and I play via Ubisoft Connect instead.

**Comment by beeradmoore** [comment]
Hey @Thortok,
Are you using DLSS Swapper [v1.0.2](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.2.0), if you are can I get you to try [v1.0.3.1](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.3.1) (pre-release) where we have improved Ubisoft Connect support.

**Comment by Thortok** [comment]
Oh I was on version 0.9.9.0 I thought it auto-updated. I'll try 1.0.2 first

**Comment by beeradmoore** [comment]
All good. Glad we got that sorted nice and quickly!

**Comment by Thortok** [comment]
Thanks for the quick help!

Unrelated, but I'm hoping you either already do or will in the future support swapping out the other DLSS files too. https://www.techpowerup.com/download/drivers/

Not just the main DLSS file but also the frame generation file and the ray reconstruction file, so 3 files total.

Maybe you already do this but it's hard to tell from the app since only a single version number is given.

Either way thanks again!

**Comment by beeradmoore** [comment]
All over it ;) 

But more tricky than adding new downloads as the app UI is going to need to be able to handle multiple dropdown types. This will be part of the next major update which also involves being able to manually add games as well.
