### ISSUE TITLE
[BUG] DLSS-Swapper does not start at all

### ISSUE THREAD

**Issue by Biggsis** [beeradmoore/dlss-swapper#178]
I installed DLSS-Swapper, neither the installed version nor the portable version do start at all.

I can see in the taskmanager that the app is started but after 2 seconds ends without notice and without showing anything.

Start as administrator does not work either.

I have Windows 11

**Comment by beeradmoore** [comment]
Hey @Biggsis ,

A common reason for this is FPS limit tools such as RTSS hook into DLSS Swapper and cause it to crash.

With latest version of RTSS this is no longer an issue. But first I'd check for those tools and add DLSS Swapper to their ignore lists.



If that doesn't fix it with the portable version in its own directory there should be a folder called StoredData, and inside that one called temp.

Are there any log files in there? And if there are could you please attach them below.

If it's still broken can you let me know anything about your system that may be different from mine, eg using another language other than English or something

**Comment by Biggsis** [comment]
Hello,

you are right, thank you for this. I had the MSI Afterburner running like always, closing the MSI solves the problem.
Now the DLSS-Swapper is running, but still useless for me, I wanted to change the DLSS version for my MSFS installation. Unfortunately my MSFS version is the store version and as such is installed in \Winapps and so does not show up in DLSS-Swapper.
I was unable to replace the DLL manually so my hope was DLSS-Swapper. Oh well, looks like there is nothing I can do about it. But a big thanks for pointing me to my problem.

**Comment by beeradmoore** [comment]
MSFS pops up every now and then as a problem game, but it has been quite a few in the past week (see #177). Installing via Xbox App should work, but I am uncertain if something has changed recently and maybe it isn't.

I'll have to look into it someday to see what the correct process is to install it, or if it has changed and will no longer work.
