### ISSUE TITLE
Add local games 

### ISSUE THREAD

**Issue by inseyven** [beeradmoore/dlss-swapper#179]
We need an option to add our local games to the swapper.
Having steam and other platforms is a good way to detect games, but *ehem* "non official" platforms exist e.e

**Comment by beeradmoore** [comment]
Hey @inseyven,
Local games are being added as a part of #8. If you'd like to hear of updates subscribe to that or hit the star feature from the main repo page to be notified of new releases (I forget if its star, it's something over there)
