### ISSUE TITLE
[BUG] v1.03 never starts up, v1.00 runs but does not find MSFS

### ISSUE THREAD

**Issue by AlHeeley** [beeradmoore/dlss-swapper#187]
**Describe the bug**
Installed latest v1.03 but it never runs or starts. Reverted to v1.00 as I heard that was more stable.

**To Reproduce**

double click dlss swapper, nothing happens.
reinstall v1.00 and the program runs, lists 2 of the 2 games I have dlss on but misses the rest of them
Found: Metro Exodus, War thunder
Misses: MSFS, Red Dead Redemption

**Comment by beeradmoore** [comment]
Do you happen to have RTSS or MSI Afterburner installed and running?

If you close them and 1.0.3 starts fine that is a known issue. Later versions of RTSS fix this, however 1.0.4 should have a fix in DLSS Swapper itself. If this is your problem I am hoping to get it out in a day or two as a preview if you would be interested in trying.

**Comment by AlHeeley** [comment]
My issue was solved by relocating the msfs encrypted folder within the xbox app, after finally finding a youtube video from someone with exactly the same issue. This allowed unrestricted access to the contents of the folder including being able to update/replace the dlss dll and the dlssg to  fsr3 dll.
Once it was unencrypted, the dlss swapper worked fine, i updated to the latest version again and that worked fine.
________________________________

**Comment by beeradmoore** [comment]
Glad to hear you got it sorted
