### ISSUE TITLE
[BUG] [1.0.4.0] "Double" entry with DLSS 3.5.10 displayed

### ISSUE THREAD

**Issue by Rool-IO** [beeradmoore/dlss-swapper#191]
**Describe the bug**
After updating from 1.0.3.1 to 1.0.4.0 I have a blank entry showing up with DLSS version 3.5.10
If I group games from the same library, it shows up in the GOG section but I don't have any other GOG installed game (Galaxy or offline)

**To Reproduce**
Don't know how, it just is

**Expected behavior**
No blank entry displayed

**Screenshots**
![2023-12-25 113613](https://github.com/beeradmoore/dlss-swapper/assets/22157095/8f6017c6-40dd-4ff7-91bb-9c24a305fa1c)
![2023-12-25 113551](https://github.com/beeradmoore/dlss-swapper/assets/22157095/f30aaa71-c72b-4754-8d59-275cf76cea2a)

**Additional context**
I tried to find out what nvngx_dlss(*).dll file could be left somewhere in GOG Galaxy's sub-folders (no other GOG game installed elsewhere anyway) but I can't figure it out as there's only the ones from installed games.

**Comment by Rool-IO** [comment]
So it's not a blank entry, it's a nonsensical double :
![image](https://github.com/beeradmoore/dlss-swapper/assets/22157095/eb1717ce-783a-489d-bcde-5beb0d693097)

**Comment by beeradmoore** [comment]
First thought was to check dark mode and yep 2 issues.

Text issue.

I'll grab phantom liberty and see why this is. Does it show up as one entry when you are looking in Steam at your library?

**Comment by Rool-IO** [comment]
Thanks for looking into this.

It does only show as one entry but it's in GOG Galaxy, not Steam. But if added as a non-steam game, it only shows as one entry in there too.

**Comment by beeradmoore** [comment]
Oh I see now.

I'll look into
- white text in light mode
- game showing up in GOG twice, once without an image
- non-steam game being added into Steam itself shows in the Steam list as well (I think that's what you mean?)

**Comment by Rool-IO** [comment]
No, I just meant the GOG Galaxy and Steam desktop clients respectively

**Comment by beeradmoore** [comment]
Looking into it and found the problem. It isn't anything to do with Steam as to why its doubling up.

GOG Galaxy creates a second entry for installed game if a game is a DLC. That is why Phantom Liberty shows up like that. I double checked by grabbing some other random DLC of one of my other test games.

<img width="589" alt="image" src="https://github.com/beeradmoore/dlss-swapper/assets/904737/ecf6a5aa-89c7-4697-8474-f3f91067b096">

Lucky enough the entry of the DLC is easy enough to determine its a DLC and I can hide it.

<img width="728" alt="image" src="https://github.com/beeradmoore/dlss-swapper/assets/904737/90f9ce73-3cc9-4607-9853-6f51ec1ad2ab">

**Comment by Rool-IO** [comment]
Great news ! Glad it's an easy fix (I guess the text one is too)

**Comment by beeradmoore** [comment]
Thanks for reporting it! I'll close this issue and let you know when a release is out (may be a day or two incase any other issues pop up)

**Comment by Rool-IO** [comment]
Apologies for this late update : I forgot to mention I'm using the following system option for the theme (if it's of any help for the text issue)

**Comment by Rool-IO** [comment]
Hey @beeradmoore , sorry to ask but is there any progress on an update with those fixes ?

**Comment by beeradmoore** [comment]
Hey @Rool-IO
No, I am the sorry one. This was fixed long ago but I forgot to get it published. I went on and instead stuck my head into the DLSS 3/FG updates. 

This is now published here, https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.5.0

Thanks again for filing an issue, and thanks for bumping this to remind me!

**Comment by Rool-IO** [comment]
No problem, that's good stuff to get your head stuck into. I had mine stuck into it as well.

You're very welcome. Thanks a lot.
