### ISSUE TITLE
MSFS Not Found in V 1.0.4.0 - Non Standard Store Installation [BUG] 

### ISSUE THREAD

**Issue by Kittster** [beeradmoore/dlss-swapper#194]
**Describe the bug**
My MSFS is installed to a non Standard Folder to keep the folder structure simpler.  DLSS Swapper Is not finding my MSFS 2020 Installation.  I installed it to: C:\MSFS2020 Packages

**To Reproduce**
1. Go to 'C:\Program Files\DLSS Swapper and run DLSS Swapper.exe as Administrator'
2. Click on 'C:\Program Files\DLSS Swapper\DLSS Swapper.exe'
3. Scroll down to 'I just get a blank screen under the Games tab'
4. See error: No error message

**Expected behavior**
I expected to see an Icon of my MSFS Installed Game but got a blank screen under games with Filter set to Hide non-DLSS games

**Screenshots**

**Additional context**
I have my filter set to the following: 
  Hide Non-DLSS Games
  If I do not hide Non-DLSS Games, then it finds my Steam game called Railroader but it is not a DLSS supported game.
  
 Settings:
 Game Libraries - All Libraries Enabled or Disabled does not make any difference.
 
Any help you can provide would be most welcome.
   

![DLSS Swapper Missing MSFS - 01](https://github.com/beeradmoore/dlss-swapper/assets/67450576/c5bf9856-20b2-4795-bc31-3245d59184cf)
[dlss_swapper_20231226.log](https://github.com/beeradmoore/dlss-swapper/files/13773314/dlss_swapper_20231226.log)
![DLSS Swapper Missing MSFS - 02](https://github.com/beeradmoore/dlss-swapper/assets/67450576/c66cac3b-7b4a-4859-b339-b473c3d63946)

**Comment by beeradmoore** [comment]
Hey @Kittster , 
When you say you installed it there, do you mean the Xbox/Windows Store apps or do you mean the thing that happens when you launch MSFS for the first time and it downloads a bunch of stuff?

**Comment by Kittster** [comment]
Thx Brad, the latter where I told MSFS where to install the Official program and it creates the Common App folder. I'm not sure where Xbox is actually installed. I open the Xbox Store and launch it from thd installed list of games. Sent from Kitt's Samsung...
-------- Original message --------From: Brad ***@***.***> Date: 12/26/23  3:49 PM  (GMT-06:00) To: beeradmoore/dlss-swapper ***@***.***> Cc: Kittster ***@***.***>, Mention ***@***.***> Subject: Re: [beeradmoore/dlss-swapper] MSFS Not Found in V 1.0.4.0 - Non Standard Store Installation [BUG]  (Issue #194) 
Hey @Kittster ,
When you say you installed it there, do you mean the Xbox/Windows Store apps or do you mean the thing that happens when you launch MSFS for the first time and it downloads a bunch of stuff?

**Comment by Kittster** [comment]
Brad, this is a corrected update to my earlier comment.

 

Thx Brad, the latter where I told Microsoft Store where to install the Official program and it creates the Common App folder. I'm not sure where Xbox is actually installed. I open the Microsoft Store, click on the Library menu on the lower left corner and it takes me to the Library window.  I select the Games tab and launch it from the list of games and it is called: Mirosoft Flight Stimulator – Xbox Game Studios.

 

Thanks – Kitt Prible

**Comment by beeradmoore** [comment]
I don't own it, but I have it for free through Game Pass. If I install through the Microsoft Store it also shows up in the Xbox app (both are connected within Windows).

When I install it and launch it then wants to download ~150GB. I put this in `C:\MSFS2020\`, I let it install and then I check DLSS Swapper and it shows up.

Can you go to the Windows Store page of the version you have installed and hit share -> copy link
<img width="537" alt="image" src="https://github.com/beeradmoore/dlss-swapper/assets/904737/366b7be9-06e8-4cad-b0f0-682cfefbee53">
(share link is on the lower right like this)

There are a few threads about MSFS ([here](https://github.com/beeradmoore/dlss-swapper/issues/140#issuecomment-1603285522), [here](https://github.com/beeradmoore/dlss-swapper/issues/177)) where people got it to work by moving the install directory (or re-install the 2gb game and pointing it at the 150gb data file that already exists) directory via the Xbox App. I can't give more detailed instructions because even if I install via the Windows Store it works fine as it puts the game in an `XboxGames` specific folder.

**Comment by Kittster** [comment]
Thanks Brad, let me take a look at this tomorrow and see If I can figure out what it did and what you are asking.  I’m a little skeptical about losing the whole app playing around with installing or moving it at month end, and year end to boot.  I will need to be fresh to do it and had a long day already today.

Thanks – Kitt Prible

**Comment by Kittster** [comment]
Brad, I went to the Microsoft Store and looked up my Microsoft Flight Simulator and clicked the Share button to produce this link I can share with you.  I'm still looking behind the scenes to see what else I can find from some tips you sent.

https://www.microsoft.com/store/productId/9NRRJLLXM68V?ocid=pdpshare

**Comment by Kittster** [comment]
Brad, I have discovered if I Open the Microsoft Store and go into Library then click on select MS Flight Simulator where I usually just hit the Play button, I can scroll down and click on a button called Open Xbox App then it takes me to this screen
![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/6660cc5b-ef70-406b-8186-2679850280f1)

From there it launches this Xbox screen and there is a 3 dot menu I can select which opens up the following screen to share or manage, or uninstall.
![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/e451d8d9-4c0e-4930-ae62-31f7ed25b83c)

**Comment by Kittster** [comment]
Uh Oh, I clicked on the Move button inadvertently and it started moving the app.
![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/7340b00b-4f47-492d-9d56-b789ed425144)

**Comment by Kittster** [comment]
Well guess what, it worked.

I just moved 2 GB and under a folder called:  C:\XboxGames\Microsoft Flight Simulator

![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/8045efea-dc83-4860-b4b4-8a8bb192ae4e)

**Comment by Kittster** [comment]
When I run the DLSS Swapper, it now shows up as seen below.

![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/9b9cbbd4-eaa8-4561-bb56-156346e29864)

**Comment by Kittster** [comment]
When I ran the DLSS Swapper again, it found it with an old DLSS file

![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/3db460e6-9525-417c-9afc-f20a94ce2edb)

**Comment by Kittster** [comment]
I downloaded the latest DLSS File and did the swap and this is what I have now.

![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/e07dc840-c3ff-4849-8285-fc187aa36c03)

**Comment by Kittster** [comment]
I'm about to give it a try and see how she behaves and also if MSFS will start up for me after I made the move.

I'll get back to you.

**Comment by Kittster** [comment]
Well Brad, I would have to say that is a beautiful thing.  It was so easy after it found MSFS and while I did not notice a huge improvement with the latest DLSS installed, at least I know I have the latest version running and with just a couple of clicks I can keep it updated going forwards.
Thank you for your patience with me.

**Comment by beeradmoore** [comment]
I am glad to hear you got it working. And thanks for the very deteailed notes on the process. Do you mind if I use those screenshots for a MSFS2020 guide to help others in the future?

**Comment by Kittster** [comment]
Thanks Brad for tge kind words. Yes, please go ahead and use them anyway you can to help others. Please don't close this ticket until tomorrow. I have another question to ask in an unrelated matter and believe you can help. I tried to do one mire thing today and may have renamed the wrong file. It is related, but has nothing to do with DLSS Swapper. I'll explain more tomorrow as having one more dinner outing in a few moments. Sent from Kitt's Samsung...
-------- Original message --------From: Brad ***@***.***> Date: 12/28/23  4:59 PM  (GMT-06:00) To: beeradmoore/dlss-swapper ***@***.***> Cc: Kittster ***@***.***>, Comment ***@***.***> Subject: Re: [beeradmoore/dlss-swapper] MSFS Not Found in V 1.0.4.0 - Non Standard Store Installation [BUG]  (Issue #194) 
I am glad to hear you got it working. And thanks for the very deteailed notes on the process. Do you mind if I use those screenshots for a MSFS2020 guide to help others in the future?

**Comment by Kittster** [comment]
Actually Brad if you have another way I can reach you tomorrow then I can fill you in w/o mesdong up the main concept if this topic because it really is closed. Sent from Kitt's Samsung...
-------- Original message --------From: Brad ***@***.***> Date: 12/28/23  4:59 PM  (GMT-06:00) To: beeradmoore/dlss-swapper ***@***.***> Cc: Kittster ***@***.***>, Comment ***@***.***> Subject: Re: [beeradmoore/dlss-swapper] MSFS Not Found in V 1.0.4.0 - Non Standard Store Installation [BUG]  (Issue #194) 
I am glad to hear you got it working. And thanks for the very deteailed notes on the process. Do you mind if I use those screenshots for a MSFS2020 guide to help others in the future?

**Comment by beeradmoore** [comment]
Best way to communicate with me is via Twitter DM (https://twitter.com/beeradmoore).
But I am more than happy to give the other bit of help you want in this thread.

**Comment by Kittster** [comment]
Thank you Brad.  I did figure out my other issues (non related) this morning (oooperator error – missed a step in the instrurctions).

Thank you for your willingness to offer to help.   

I am enjoying the DLSS Swapper and am amazed at how many versions behind I was flying considering I usually upgrade my NVIDIA Drivers quite often.

 

Have a Happy New Year.

**Comment by Kittster** [comment]
![image](https://github.com/beeradmoore/dlss-swapper/assets/67450576/d04aa3a8-b501-4ea7-bf27-bf206afa517b)

I don't think the last graphic came in properly.

**Comment by beeradmoore** [comment]
Apparently NVIDIA drivers have the ability to inject a newer version, but I think only one game was announced to do it (cyberpunk2077) and even then I don't recall ever seeing it. 

It's up to developers to update their game. Updating may mean a whole lot of other validation and can cause all sorts of problems.

Happy holidays and happy new year. Glad you got things sorted! If you have any other questions or comments feel free to open a new issue.

**Comment by Kittster** [comment]
Interesting. Thx for the info. I see you live down under mate. Guess you will get to New Years before we fo back in St Louis. Sent from Kitt's Samsung...
-------- Original message --------From: Brad ***@***.***> Date: 12/29/23  2:46 PM  (GMT-06:00) To: beeradmoore/dlss-swapper ***@***.***> Cc: Kittster ***@***.***>, Comment ***@***.***> Subject: Re: [beeradmoore/dlss-swapper] MSFS Not Found in V 1.0.4.0 - Non Standard Store Installation [BUG]  (Issue #194) 
Apparently NVIDIA drivers have the ability to inject a newer version, but I think only one game was announced to do it (cyberpunk2077) and even then I don't recall ever seeing it.
It's up to developers to update their game. Updating may mean a whole lot of other validation and can cause all sorts of problems.
Happy holidays and happy new year. Glad you got things sorted! If you have any other questions or comments feel free to open a new issue.
