### ISSUE TITLE
[Feature request] Add other games...

### ISSUE THREAD

**Issue by fram446742** [beeradmoore/dlss-swapper#198]
**Is your feature request related to a problem? Please describe.**
I have games from other libraries apart from Steam, GOG, Epic, Ubisoft, Xbox

**Describe the solution you'd like**
It would be great to be able to add other games (obviously that supports dlss), maybe providing the path to the executable.

**Comment by beeradmoore** [comment]
Hey @fram446742 , 
We have identiifed some other game launchers and have a super ticket [here](https://github.com/beeradmoore/dlss-swapper/issues/71) tracking those. If we are missing any can you please let me know.

As for manually adding games, that is begin tracked [here](https://github.com/beeradmoore/dlss-swapper/issues/8) and is actively being worked on right now :)
