### ISSUE TITLE
[Feature request]  Add DLSS swap support for DCS World 

### ISSUE THREAD

**Issue by The3dVehicleguy** [beeradmoore/dlss-swapper#199]
I would like to be able to swap out my DLSS version for Eagle Dynamics DCS World. Currently there is no support and the dlss-swapper doesn't detect it. 

**Describe the solution you'd like**
I'd like to be able to swap the version of DLSS in DCS World as I wanna test out if changing to a more up to date version would add more performance.

**Comment by beeradmoore** [comment]
Hey @The3dVehicleguy,
How is DCS installed? Is this via Steam or does it have its own installer?

**Comment by The3dVehicleguy** [comment]
DCS World has its own installer but there is also a Steam version of the game as well. I use the standalone DCS Installer. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Brad ***@***.***> Date: 1/7/24  3:35 AM  (GMT-05:00) To: beeradmoore/dlss-swapper ***@***.***> Cc: Thomas Ray ***@***.***>, Mention ***@***.***> Subject: Re: [beeradmoore/dlss-swapper] [Feature request]  Add DLSS swap support for DCS World  (Issue #199) 
Hey @The3dVehicleguy,
How is DCS installed? Is this via Steam or does it have its own installer?

**Comment by beeradmoore** [comment]
For adding DCS you'll need the "add manual game feature" currently under construction. It will be released in the v1.1 update.

You can track progress by subscribing to #8.

Closing this issue for now, hoping to get that update done soon.
