### ISSUE TITLE
Support for DLSS in Windows Store/Xbox App games

### ISSUE THREAD

**Issue by beeradmoore** [beeradmoore/dlss-swapper#2]
Directories will always be in the same places but folder permissions may get in the way. Especially for writing into them.
How does GeForce Now do it?

**Comment by beeradmoore** [comment]
So fun fact for this one, games directory has its version in it. So if you update your game while DLSS Swapper is open (and support was added) the game directory will no longer be found.

Sample game directories:
- C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.17.1101.0_x64__8wekyb3d8bbwe\
- C:\Program Files\WindowsApps\HelloGames.NoMansSky_3.66.12428.0_x64__bs190hzg1sesy\

**Comment by beeradmoore** [comment]
Bringing in context from another thread, 

> With the old Xbox app and installing games into the WinApps folder this can't happen.
> 
> With the new preview Xbox app where it can install into any directory this may be possible. I'm still waiting for the preview to become available for me to look at if this is possible then.

I was able to make contact with a product manager regarding getting help supporting this. Watch this space.

**Comment by beeradmoore** [comment]
Drives have a hidden `.GamingRoot` file in the root which contains information on the library path, although there is some additional characters in there.

**Comment by revanmj** [comment]
Regarding your GFN note from description - as far as I know GFN does not support MS Store games. Only Steam, Epic and uPlay in general, Origin in lesser extent, some exceptions from GOG and game specific launchers (like Wargaming one)

**Comment by beeradmoore** [comment]
Was more regarding how does GFN know what my windows games are. I was never able to really find something like Forza Horizon 4 (isn't DLSS supported) install info but GFN does. 

Either way those games don't matter as much as it's only games via the Xbox app that we can actually modify files for anyway. And even that is only if they support the advanced install options.

**Comment by beeradmoore** [comment]
100% meant GFE, my bad.

**Comment by draco1544** [comment]
any update on this ?

**Comment by beeradmoore** [comment]
@draco1544 , not yet. Low number up upvotes means low priority. Feel free to share this issue and request upvotes though.

**Comment by beeradmoore** [comment]
This has been added in the [v0.9.12.0 preview](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.12.0). Closing for now, if you have any issues with Xbox app compatibility please file new issues.

**Comment by revanmj** [comment]
First feedback - any chance for requesting admin rights in app just for swapping operation? Right now, for this to work, entire app must be launched with admin rights.

**Comment by beeradmoore** [comment]
I am confused, it does not require admin rights 🤔

**Comment by revanmj** [comment]
It does for me. When app is launched normally, swap fails with generic error that suggest repairing game files. Works fine when launched as admin (and I confirm this from manual swapping - Xbox games catalog alwas asks me for admin rights when changing files in it).

**Comment by revanmj** [comment]
Though I have a feeling this may be an issue only on machines upgraded to 10/11 as Xbox app generally had many issues on mine machine that was not formatted since Vista unlike a laptop which had 11 clean installed.

**Comment by beeradmoore** [comment]
Interesting... Can you file a new ticket so we can track this issue there?

For me on both of my systems (neither of which I have done funky things with WindowsApps folder) I can write to the game folder while using my normal accounts. I can't view the WindowsApps folder itself, so if I am in a game folder and attempt to go up a directory it says no.

For reference of what I have going on here - one system is Win11 where I am logged in with my MS account. The other system is Win10 where I am logged in as a local account. Both systems I am logged into the same MS account for Xbox app.

This new feature works by using the `.GamingRoot` files which are stored on the root of every drive. It contains the location of your Xbox games (what is the right word for this, Xbox app games?) are installed on that drive. It then lists these directories and compares against a list of every package installed on your computer to say. It then keeps a reference to the game location in WindowsApp folder which as I said above, the individual folders (at least these ones) are fully writable to me. The files added here also instantly add to the other folder (C:\XboxGames\ for me)

I am in Xbox app Insider and I have used the [Advanced Installation and Management Features](https://news.xbox.com/en-us/2021/11/18/advanced-installation-and-management-features-available-for-insiders-through-the-xbox-app-for-windows/) for the Xbox app, but the games I had tested with were not "advanced", they just let me install the game location.

My test game was The Ascent from Game Pass.

(Will copy this to the new issue and continue there, but for now I need food and sleep)
