### ISSUE TITLE
[BUG] - DLSS Swapper installation failed - 0x800700D

### ISSUE THREAD

**Issue by KaiAsk** [beeradmoore/dlss-swapper#21]
As I install the program, it comes up with an error, including 0x8007000D. I found this is normally seen for Windows updates, but has shown up for this application installation too.

![dlss-swapper failed](https://user-images.githubusercontent.com/90113692/132107643-aba085d0-c616-4944-bc79-d1f33482aa41.JPG)

I have correctly installed the certificate and have followed the steps, but always leading to this problem.

**Comment by beeradmoore** [comment]
Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though,  Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).

**Comment by DrLuuu** [comment]
> Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though, Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).

hmmm that 0.9.0.0 fixed my issue "App Installer failed to install package dependencies. Ask the developer for  package. "
but it seems like there is no DLSS available and it's not recognizing games
