### ISSUE TITLE
[Feature request] DLSS preset selection for a given version

### ISSUE THREAD

**Issue by alexismarret** [beeradmoore/dlss-swapper#211]
It would be great to be able to select a DLSS preset (A, B, C...) for a given DLSS version

**Comment by beeradmoore** [comment]
Hey @alexismarret , can you reference any material on what those presets are and how they are actually applied?

**Comment by alexismarret** [comment]
Take a look here for a per game tool that has this feature: https://www.nexusmods.com/site/mods/550?tab=description
And here's a video comparing presets in a few games: https://www.youtube.com/watch?v=-BckcPSq7Oo&t=4s

**Comment by beeradmoore** [comment]
Ah yep, gotya. Looks like it's part of DLSSTweaks, there is an open issue to support DLSSTweaks here #132.

Is it ok if I close this issue and move the feedback of preset selector into that issue?
