### ISSUE TITLE
[BUG] No Steam games are detected

### ISSUE THREAD

**Issue by ziher123** [beeradmoore/dlss-swapper#212]
**Describe the bug**
No Steam games are detected. Running app as admin doesn't help. 

**To Reproduce**
Always.

**Expected behavior**
Dlss swapper should find Steam dlss enabled games, specifically MSFS and RE8 but it searches for them indefinitely. Disabling Hide non-DLSS games filter doesn't work.

**Screenshots**
![Image2](https://github.com/beeradmoore/dlss-swapper/assets/89880695/71d77eaf-d3a5-42fd-bd16-37c01e8074fa)

This is a prompt after restarting the app: 
![Image3](https://github.com/beeradmoore/dlss-swapper/assets/89880695/30d6cbf9-4ab8-45d4-b1ec-c54fc5454068)

**Additional context**
RE8 install dir:
K:\SteamLibrary\steamapps\common\Resident Evil Village BIOHAZARD VILLAGE
MSFS install dir:
X:\Program Files (x86)\SteamLibrary\steamapps\common\MicrosoftFlightSimulator

Log set to verbose has this:
2024-03-28 22:07:12.987 +01:00 [INF] App launch - v1.0.5.0
2024-03-28 22:07:13.247 +01:00 [INF] ThemeWatcher.cs:101 Start - Light, False

Is there a way to manually add games that i'm unaware of?

**Comment by beeradmoore** [comment]
That is odd that the games are not showing up.

Does the loading wheel ever disappear? 
If not it means it's likely dying trying to read the Steam manifest files. Odd that it isn't reporting anything in the error log though. Thanks for providing that as well as it would be one of the first things I'd ask for.

 From memory MSFS "install" is actually just a launcher which then installs the game files elsewhere, is RE8 the same deal? 

Just to sanity check the files are where we expect, if you go to `K:\SteamLibrary\steamapps\common\Resident Evil Village BIOHAZARD VILLAGE` and `X:\Program Files (x86)\SteamLibrary\steamapps\common\MicrosoftFlightSimulator` in Windows Explorer and search for `nvngx_dlss.dll` is it found? 

The way DLSS Swapper works for loading Steam games is it first loads the `libraryfolders.vdf` folder which should be in the `steamapps` folder of your Steam install, for me this is `C:\Program Files (x86)\steamapps\` (it loads Steam install path from registry, so it shouldn't matter if you have a different install path).

Can you confirm `libraryfolders.vdf` is there? If it is can you open it up (notepad, text edit, vscode should all work well enough) to see that it lists your `K:\SteamLibrary\` and `X:\Program Files (x86)\SteamLibrary\`.

Then inside those paths it looks in `steamapps` for any `appmanifest_***.acf`, eg. `K:\SteamLibrary\steamapps\appmanifest_123456.acf`. Every game you have installed should have a corresponding `.acf` file in the `steamapps` folder they are installed in.

The number in this file should be the same as the app ID, depending on what version you have installed you can find the MSFS app IDs [here](https://steamdb.info/search/?a=all&q=microsoft+flight+simulator) and RE8 ones [here](https://steamdb.info/search/?a=all&q=resident+evil+village) (they are also only the ones that say game under it, not dlc.

From the install path we get from the `.acf` files we then can then look for the above mentioned `nvngx_dlss.dll`.

If any one of these is being read incorrectly it could cause the Steam loading to fail. It's possible it failed to load somewhere along this whole setup and it isn't reporting failures in the logs.

If possible, if you could send the relevant `libraryfolders.vdf` and `appmanifest_***.acf` files for those 2 games I can run them through DLSS Swapper locally here and see where it dies.

**Comment by ziher123** [comment]
Loading wheel kept running for few hours until i exited.

I think RE8 is 'native' steam install but can't recall. Anyway, there's no nvngx_dlss.dll in RE8 main folder (my mistake, i checked in game and it has FSR only).

I forgot about ACC, it's nvngx_dlss.dll is in folder
L:\Program Files (x86)\SteamLibrary\SteamApps\common\Assetto Corsa Competizione\AC2\Plugins\DLSS\Binaries\ThirdParty\Win64

MSFS does have nvngx_dlss.dll in main folder. 

Libraryfolders.vdf file is in O:\Program Files (x86)\SteamW10\steamapps folder and it lists all library folders correctly.

Attached files you asked for.
Libraryfolders.vdf is from folder:
O:\Program Files (x86)\SteamW10\steamapps
appmanifest_1250410.acf is from folder:
X:\Program Files (x86)\SteamLibrary\steamapps
appmanifest_805550.acf is from folder:
L:\Program Files (x86)\SteamLibrary\SteamApps

[steamapps.zip](https://github.com/beeradmoore/dlss-swapper/files/14803230/steamapps.zip)

**Comment by beeradmoore** [comment]
Thanks for attatching those files. I was able to run them through the program without issues, at least up until it tried to load DLSS files as those game installs don't exist here.

I have added a bunch of logging into the Steam game load code and published a pre-release build v1.0.5.1 for you to try [here](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.5.1). Portable or Installer should work fine, if you use portable version the logs are in `StoredData/temp/` of its directory.

I also added some sanity checks to output each of the output types so we can confrim they are being logged correctly.

If you could get v1.0.5.1, launch it, disable other libraryes, set logging to verbose, then restart the application and have a look at/attatch the log. Hopefully it can try point us in the right direction.

**Comment by ziher123** [comment]
It worked:)

![Steam](https://github.com/beeradmoore/dlss-swapper/assets/89880695/1d3f85b4-3175-4c0d-9365-a448c04d236b)

Thanks for looking into this, i attached log file in case you want to check it out.
[dlss_swapper_20240330.log](https://github.com/beeradmoore/dlss-swapper/files/14811506/dlss_swapper_20240330.log)

**Comment by beeradmoore** [comment]
Mmm... I like that it worked, but I don't see any reason why it worked 😅
None of the additional logging that should report errors fired so as far as I can tell it processed everything as it normally did.

Either way, I'll keep the updated error checks in and remove some of the more detailed logging so we don't clog logs with stuff that isn't required.

Closing issue for now. 

Thanks for the detailed responses, helped dig into it a lot easier.
