### ISSUE TITLE
[BUG] 0x80070570 Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed

### ISSUE THREAD

**Issue by weclock-droid** [beeradmoore/dlss-swapper#22]
completed the steps to trust the app and got this when installing
App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)

**Comment by beeradmoore** [comment]
Hey @weclock-droid , what happens if you re-download the package from our [releases tab](https://github.com/beeradmoore/dlss-swapper/releases/download/v0.9.3.0/DLSS.Swapper_0.9.3.0_x64.msixbundle) and then try install that directy?

**Comment by mychaelhoward** [comment]
> 
> 
> Hey @weclock-droid , what happens if you re-download the package from our [releases tab](https://github.com/beeradmoore/dlss-swapper/releases/download/v0.9.3.0/DLSS.Swapper_0.9.3.0_x64.msixbundle) and then try install that directy?

had the same error redownloading with that link fixed it for me

**Comment by beeradmoore** [comment]
Not entirely sure what went wrong there. But glad its working now.

**Comment by weclock-droid** [comment]
it works of the releases tab for sure.

**Comment by solomoncyj** [comment]
i think he/she got it when running `add-appxpackage ./` in the built releases bin folder
