### ISSUE TITLE
[Feature request] Wuthering Waves

### ISSUE THREAD

**Issue by ElenaNya** [beeradmoore/dlss-swapper#220]
Add to change dlss in Wuthering Waves, this is both a suggestion and a bit of a question, maybe it's already supported and I have some problem.

**Comment by beeradmoore** [comment]
Hey @ElenaNya ,
Does that game have DLSS in it already? DLSS Swapper won't add DLSS to games that don't have it.

What game library did you download it from? DLSS Swapper scans libraries to find games, so if it's one that isn't supported that could also be why it isn't showing up.

**Comment by ElenaNya** [comment]
> Hey @ElenaNya , Does that game have DLSS in it already?DLSS Swapper won't add DLSS to games that don't have it.
> 
> What game library did you download it from? DLSS Swapper scans libraries to find games, so if it's one that isn't supported that could also be why it isn't showing up.

Yes, dlss 3.5.0 and the corresponding file, but dlss swapper doesn't see the game

**Comment by beeradmoore** [comment]
Thanks for the quick response.

If the game is downloaded from their own site then DLSS Swapper currently has no way to know it exists. The way it works is by looking at your Steam config, your GoG config, etc, to then know where to look for games. This also gives extra info such as game name, cover image, etc. 

In the next major update DLSS Swapper allows you to add a game manually. Unfortunately that means you'll have to wait for that update for Wuthering Waves to work with DLSS Swapper. 

In the mean time you can use DLSS Swapper to download and export up to date `nvngx_dlss.dll` file which you can replace in that games folder manually (backup up the original `nvngx_dlss.dll` file) to accomplish the same thing. Alternatively you can download DLSS from [TechPowerUp](https://www.techpowerup.com/download/nvidia-dlss-dll/) and do that manual copy.

**Comment by FidRay16** [comment]
Try to download it from EGS
![image](https://github.com/beeradmoore/dlss-swapper/assets/101008675/d3be3324-42a2-427c-a8cf-faf82dcc834c)

**Comment by FidRay16** [comment]
> In the next major update

When does it come out? I look forward to it

**Comment by beeradmoore** [comment]
> When does it come out?
Can't give an ETA as this project is only done in my spare time. Can't predict that unfortunately :P

**Comment by FidRay16** [comment]
Ok. Got it. Just waiting for it since Jan
