### ISSUE TITLE
[BUG] Steam library fails to load

### ISSUE THREAD

**Issue by thepwrtank18** [beeradmoore/dlss-swapper#222]
**Describe the bug**

**To Reproduce**
1. Have Steam and only Steam enabled as a library
![image](https://github.com/user-attachments/assets/fc64106b-79b8-4ced-b14e-a0051a7518a4)
2. Press Save
3. Loads infinitely
4. Close and reopen
5. See issue again
![image](https://github.com/user-attachments/assets/60cc34d9-3d93-4fb1-877d-655c9abcbbd3)

**Expected behavior**
DLSS Swapper should show the games on my Steam library.

**Comment by thepwrtank18** [comment]
Seems to work after a few minutes, but it appears to show as if it errored anyway immediately after opening. This is on the 1.0.5.1 experimental build.

**Comment by beeradmoore** [comment]
Hey @thepwrtank18 , 

For quick and easy elimination of problems can you confirm you are using the latest released version v1.0.5.

This looks like issue #212.  For that we tried the test build [here](https://github.com/beeradmoore/dlss-swapper/releases/tag/v1.0.5.1) and it worked. Can you give that a go?

**Comment by beeradmoore** [comment]
Beat me to the reply. If it's still not showing games, can you go into the apps settings (cog in the lower left) and ensure logging is on Verbose, and if it is, can you upload a log here. If it isn't can you change it to verbose and then restart the app can cause the issue again.
