### ISSUE TITLE
[BUG] File system error -2147219195 

### ISSUE THREAD

**Issue by jtoya85** [beeradmoore/dlss-swapper#23]
I have ZERO idea what is going on but whenever I try to install the app a window appears for half a second then an error pops up
![Untitled](https://user-images.githubusercontent.com/90115330/132109011-e57d07d5-4b25-4413-9259-7be19b46b4ec.png)
Everything I have looked up points to the Photos app having a problem and reinstalling it can fix it. My problem is that I cannot uninstall it to even attempt to reinstall. I have performed a repair and reset multiple times, tried installing a few days ago when I first heard about it and I was getting the same problem. Help?

**Comment by beeradmoore** [comment]
Did you follow the [install instructions](https://beeradmoore.github.io/dlss-swapper/install/)?

Is that Windows 10 or 7?

**Comment by jtoya85** [comment]
> Did you follow the [install instructions](https://beeradmoore.github.io/dlss-swapper/install/)?
> 
> Is that Windows 10 or 7?

Yes I did, even at the part that says "download here" and it goes to the different page, I hit install and I get the confirmation with Chrome that asks if I want to install and I say yes. The installer(?) window pops up for half a second then disappears, without error too. Only if I download the package from here do I get the error. I'm using Windows 10
![Untitled](https://user-images.githubusercontent.com/90115330/132109272-e6c98cc5-0cfb-44ad-a5fc-c61b5675a34f.png)

**Comment by beeradmoore** [comment]
Interesting. I'll try find time to look into this error some more today.

Out of curiously are you using 32bit or 64bit Windows?
![image](https://user-images.githubusercontent.com/904737/132109624-23d212ce-f07d-4f14-8480-539f5b83ab4e.jpeg)

**Comment by jtoya85** [comment]
64 bit

**Comment by beeradmoore** [comment]
Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though,  Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).

**Comment by jtoya85** [comment]
same exact error trying to reinstall those dependencies.

**Comment by beeradmoore** [comment]
Now we both have zero idea of what is going on 😂

Looking up online I too see people talking about Paint app. I am unsure if fixing Paint is the problem, or if the problem is just reported by Paint a lot.

I did find [this](https://www.reddit.com/r/computers/comments/iuuxbm/how_to_fix_file_system_error_2147219195/g5ncst3/?utm_source=reddit&utm_medium=web2x&context=3) reddit thread where they link to something to run in powershell. I am not entirely sure what that command is doing (it looks like its re-installing every app for every user) so I can't really recommend doing it (or at least do it at your own risk).

**Comment by jtoya85** [comment]
well, I ended up reinstalling windows keeping my files and that seemed to fix the issue.

**Comment by beeradmoore** [comment]
I hate having to do do things like that :( But glad it's finally working for you.
