### ISSUE TITLE
[BUG] Not working with Dead Rising Deluxe Remaster

### ISSUE THREAD

**Issue by DreamboxMinerva** [beeradmoore/dlss-swapper#231]
Using this to change the DLSS preset in Dead Rising Deluxe Remaster, will cause the game to instant crash if you open the pause menu.

**Comment by beeradmoore** [comment]
What version of DLSS did you swap from and to?

To fix your game you can hit the reset button in the DLSS dropdown (or repair from your game launcher)

Unfortunately we can't ensure that any specific version will work with any specific game, nor can we tell users that selecting a specific version does not work with a specific game.

**Comment by DreamboxMinerva** [comment]
Nevermind, I'm stupid and mixed DLSS Swapper and DLSS Tweak (like I always do) :)

BUT, at least I can say that DLSS Swapper does work with Dead Rising without any issue to make it use the latest DLSS.

**Comment by beeradmoore** [comment]
All good :)
