### ISSUE TITLE
[BUG] Fortnite showing XeSS instead of DLSS

### ISSUE THREAD

**Issue by kunsh13** [beeradmoore/dlss-swapper#232]
Using the Latest DLSS version in Fortnite, makes it appear as intel Xess technology rather than Nvidia DLSS on an Nvidia GPU
but the game runs smoothly

**To Reproduce**
1. apply latest dlss version on Fortnite
2. open Fortnite after applying
3. go to settings
4. scroll down until you see it

**Expected behavior**
Nvidia DLSS should be shown here

**Screenshots**

![image](https://github.com/user-attachments/assets/298e896d-1fca-4741-a236-aff856c5a898)

Original :

![image](https://github.com/user-attachments/assets/df3a9162-0595-4ca4-8b9b-03ca7d231cc7)

Swapped:

![image](https://github.com/user-attachments/assets/1fffd376-93a0-467e-9f97-79c52eefa04f)

**Comment by beeradmoore** [comment]
Hey @kunsh13 ,
In that upscaler list when DLSS is normally visible, is XeSS listed as next in the list after it?

It sounds like Fortnite is checking the file version and it knows it's not what it wants, or tries to load it and it fails so it moves on.

In either case there isn't anything we can do to fix or prevent this situation.


As a side note it's very interesting that Fortnite, which is on top of their game for using new tech is using such an old version of DLSS to begin with.

**Comment by kunsh13** [comment]
> Hey @kunsh13 ,
> In that upscaler list when DLSS is normally visible, is XeSS listed as next in the list after it?
> 
> It sounds like Fortnite is checking the file version and it knows it's not what it wants, or tries to load it and it fails so it moves on.
> 
> Edit: I also think this is just using XeSS, if you are getting a great experience from that (or at least better than DLSS 2.2) you should keep using that. If not you can hit the revert button in the DLSS picker menu to put the original back.
> 
> In either case there isn't anything we can do to fix or prevent this situation.
> 
> 
> As a side note it's very interesting that Fortnite, which is on top of their game for using new tech is using such an old version of DLSS to begin with.

The DLSS option is gone
Only Intel XeSS option is appearing


But using Intel XeSS on a Nvidia GPU seems weared

**Comment by beeradmoore** [comment]
Yeah sounds like Fortnite refused to load it because it knows you changed it. That could be part of its anti-cheat measures. Always be careful using DLSS Swapper with multiplayer games, as their systems may flag you as cheating because you tampered with files.

Using AMDs FSR is just as weird, but that's the joy of these other open platforms :)

**Comment by kunsh13** [comment]
Here is a Gameplay video for better clarity:


https://github.com/user-attachments/assets/f4eb5587-7848-42d9-a7ae-1d91e4017f97

<br>


I hope using Intel XeSS on a Nvidia GPU will not break things

**Comment by beeradmoore** [comment]
There its absolutely nothing wrong with using XeSS with an Nvidia gpu :) 

Closing this issue for now. Happy fortniting!
