### ISSUE TITLE
[Feature request] custom game

### ISSUE THREAD

**Issue by Batuking1111** [beeradmoore/dlss-swapper#233]
**Is your feature request related to a problem? Please describe.**
i am looking for war thunder but i cant find

**Describe the solution you'd like**
can we add games manualy?

**Comment by Zagrthos** [comment]
This is currently Work-In-Progress as of #8.

**Comment by beeradmoore** [comment]
Like @Zagrthos said, work in progress. 

Does War Thunder have its own private launcher, or is it installed with Steam or similar?

**Comment by Batuking1111** [comment]
i installed with launcher but game have steam version too

**Comment by beeradmoore** [comment]
In theory it should be detected if you installed via Steam. But if they have their own launcher it currently won't be detected.

Work is in progress of manually adding games, that will be added when #8 is resolved. If you want to go there and hit subscribe on the side menu you an be notified of any alerts to that thread to keep updated.

There is no ETA of when that will be complete unfortunately.

I am closing this issue off for now.
