### ISSUE TITLE
[Feature request] Add support for pirated games

### ISSUE THREAD

**Issue by Wkrotik** [beeradmoore/dlss-swapper#237]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A way to select where your games are stored, so pirated games could work

**Additional context**
I know that I am asking about something, that is wrong to do, but it is what it is. so I and I guess many others would love to see ability to swap them for pirated games also. Thanks

**Comment by beeradmoore** [comment]
Yep, closing as a duplicate.

If you're going to pirate then pirate, but also please support indie developers.
