### ISSUE TITLE
[Feature request] Option to select games folder

### ISSUE THREAD

**Issue by DGVaniX** [beeradmoore/dlss-swapper#24]
I personally have all my games either installed or just copied to an external hard drive, and DLSS Swapper doesn't seem to find them all, so an option to select the games folder and have the program scan the folder for games would be nice. :)

**Comment by beeradmoore** [comment]
This one is difficult. If DLSS Swapper is told to point to folder "C:\Games\GameXYZ\", it doesn't know what game GameXYZ is, nor can it display a game image. 

A possibly solution could be to add a user interface to add a folder, name it, add a banner image, etc.

**Comment by beeradmoore** [comment]
Closing in favour of #8
