### ISSUE TITLE
[BUG] Failed to load game libraries

### ISSUE THREAD

**Issue by Shouko657** [beeradmoore/dlss-swapper#245]
**Describe the bug**
Upon starting DLSS Swapper I am greeted with "Failed to laod game libraries". Selecting the pre-selected source (Steam) and clicking save results in the program loading endlessly. Longest I have waited was 30+ mins.

**To Reproduce**
Mentioned above

**Expected behavior**
Installed games should show

**Screenshots**
<img width="1420" alt="jp2launcher_X8us6oGID1" src="https://github.com/user-attachments/assets/3b842c72-3d02-4975-9035-1f9f85f8a8ed">

**Additional context**
Used to work before but suddenly stopped working.

**Comment by beeradmoore** [comment]
Does it load instantly now or will it take 10mins every time?

**Comment by beeradmoore** [comment]
That is very odd. Is there anything you could think of why it performs like this? Like do you have lots of games installed, are they on HDDs, etc

The next release should help with this as we maintain a cache rather than load every game on every launch

**Comment by Shouko657** [comment]
I have a couple of games installed and most of them are on a SDD
