### ISSUE TITLE
[DEV BUG] Cant edit user interface

### ISSUE THREAD

**Issue by Jordonbc** [beeradmoore/dlss-swapper#25]
**Describe the bug**
When opening the project in visual studio blend it says that it's an unsupported project

**To Reproduce**
1. git clone project to pc
2. open `DLSS Swapper.sln`
3. In Solution Explorer right click on `MainWindow.xaml` (or any .xaml in Pages folder)
4. Select `Design in Blend` option

**Expected behavior**
To be able to open and edit user interface files

**Screenshots**

![](https://snipboard.io/gvCYbi.jpg)

**Additional context**
Opened with Visual Studio community 2019 (update 16.11.2)
Installed workloads:
- .NET desktop development
- Universal Windows Platform development
- Game development with C++

Can compile and run project

**Comment by cftad** [comment]
The project appears to be using [WinUI](https://microsoft.github.io/microsoft-ui-xaml/about.html), which AFAIK doesn't support visual editing via designer.
