### ISSUE TITLE
[ERROR] App Installer failed to install package dependencies. Ask the developer for  package. 

### ISSUE THREAD

**Issue by DrLuuu** [beeradmoore/dlss-swapper#28]
1. Go to 'Open the File'
2. Click on 'Install'
3. Stuck at'16%'
4. Comes up with an error "App Installer failed to install package dependencies. Ask the developer for  package. "

- Anyone has any solutions , tried unblocking the files and checking the permissions nothing helped

**Comment by beeradmoore** [comment]
Did you follow the [install instructions](https://beeradmoore.github.io/dlss-swapper/install/) and then use the dedicated [download page](https://beeradmoore.github.io/dlss-swapper/download/)?

If you installed 0.9.0.0 you may need to uninstall that first.

**Comment by DrLuuu** [comment]
> Did you follow the [install instructions](https://beeradmoore.github.io/dlss-swapper/install/) and then use the dedicated [download page](https://beeradmoore.github.io/dlss-swapper/download/)?
> 
> If you installed 0.9.0.0 you may need to uninstall that first.

Opened it correctly now with latest update but there is no DLSS.dll files , how can I install those that would show available

**Comment by DrLuuu** [comment]
I had to install 0.9.0.0 , uninstalled as you said and installed from the download page ... now it works fine

**Comment by beeradmoore** [comment]
Glad we got you on board! Enjoy :) Any other comments or feedback feel free to create more issues.
