### ISSUE TITLE
[Feature request] Support for VALORANT / LOL (RIOT GAMES )

### ISSUE THREAD

**Issue by ankushom19** [beeradmoore/dlss-swapper#29]
I would like to request the dev to add support for Valorant/ LoL (Riot Games).

**Comment by beeradmoore** [comment]
Hey @ankushom19 , DLSS Swapper does not inject DLSS into games that did not have it before. It will only upgrade the internal DLSS libraries when new ones become available. 

From what I can tell neither Valorant nor LoL support DLSS so we are unable to do this.
