### ISSUE TITLE
[BUG] Installer Error 0x80070490

### ISSUE THREAD

**Issue by htdsfa** [beeradmoore/dlss-swapper#30]
So i had this error when i tried to install : 0x80070490 "Opening the package from location DLSS.Swapper_0.9.3.0_x64.msixbundle failed"

**Comment by beeradmoore** [comment]
Hey @htdsfa , did you follow the initial [install instructions](https://beeradmoore.github.io/dlss-swapper/install/)?

Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though,  Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).

**Comment by htdsfa** [comment]
thank you it works now
