### ISSUE TITLE
[BUG] Error 0x80070570. (0x80070570)

### ISSUE THREAD

**Issue by ndagenai** [beeradmoore/dlss-swapper#31]
App shows trusted, followed the install guide more than once and step by step.

Getting this error upon attempting to install.

See picture.

![Capture](https://user-images.githubusercontent.com/44884758/132949828-bb1fbb0b-5f27-4b96-84b3-56b718c9f61d.PNG)

**Comment by beeradmoore** [comment]
Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though,  Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).

**Comment by ndagenai** [comment]
That fixed it! Thanks!

**Comment by Crimsxn09** [comment]
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)          what should i do about this?
