### ISSUE TITLE
[Feature request] Keep the color of DLSS version display

### ISSUE THREAD

**Issue by TTsdzb** [beeradmoore/dlss-swapper#35]
When the Windows color theme is light, font color of DLSS version becomes dark which is difficult to see.
For example:
![A screenshot, url: https://imgtu.com/i/4CvQ9H](https://imgtu.com/i/4CvQ9H)

I suggest that the font color should be fixed to white, or change the bar's color to white, thus we can see the version clearly.

**Comment by beeradmoore** [comment]
This has been fixed and is just waiting to be released :)

**Comment by TTsdzb** [comment]
Oh man I've just seen the previous issue about that. I'm sorry to have wasted your time.

**Comment by beeradmoore** [comment]
Is all good :)
