### ISSUE TITLE
[BUG] Install fails at 10%

### ISSUE THREAD

**Issue by farshad1997** [beeradmoore/dlss-swapper#36]
**Describe the bug**
this app have problem install for me
i certificate licence in windows and install that in trust peaple vs trust device
but i go error in install 10٪ after error please help

**Comment by beeradmoore** [comment]
Would you be able to try (re-)installing the dependencies manually (Microsoft.ProjectReunion.0.8.msix, Microsoft.VCLibs.x64.14.00.appx, Microsoft.VCLibs.x64.14.00.Desktop.appx), they are listed in the [0.9.0.0 releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.0.0). Don't install DLSS.Swapper_0.9.0.0_x64.msixbundle from there though,  Instead download the .msixbundle from the [latest release](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.3.0).
