### ISSUE TITLE
[Feature request] Support for games detected by GOG Galaxy

### ISSUE THREAD

**Issue by vfxninjaeditor** [beeradmoore/dlss-swapper#48]
**Is your feature request related to a problem? Please describe.**
This is a feature request.

**Describe the solution you'd like**
I'd love to see support for games detected by GOG Galaxy. For people who use it this would cover any game installed by any game platform like Steam, Epic Games, Uplay, or Origin.

**Additional context**

**Comment by beeradmoore** [comment]
Hey @vfxninjaeditor , thanks for reporting. This is already covered in #14 for GoG, and other platforms are in other issues. If you want to go give the issue a 👍 or leave a comment will help me gauge interest of those other platforms for when we go to add them.
