### ISSUE TITLE
Swapped Shadow on The Tomb Raider to DLSS 2.0 Issue

### ISSUE THREAD

**Issue by KedarWolf** [beeradmoore/dlss-swapper#5]
I compiled DLSS Swapper and updated this game to DLSS 2.0, the latest version.

DLSS 2.0 is supposed to support Ultrawides but no option to enable it on my 3840x1080 screen.

**Comment by beeradmoore** [comment]
If the implementation of DLSS requires the developers to add extra code to support ultra wide monitors then updating the internal DLL version won't make it suddenly work unfortunately.
