### ISSUE TITLE
[BUG] Error - Unable to update DLSS record

### ISSUE THREAD

**Issue by Audioboxer** [beeradmoore/dlss-swapper#54]
**Describe the bug**
Can't seem to check for DLSS dll updates

**To Reproduce**
1. Click refresh on downloads screen

**Expected behavior**
Check for DLSS version updates?

**Screenshots**
https://i.imgur.com/2WxVrtH.png

**Additional context**
Prior version seemed to use techpowerup website and listed up to version 2.3.2

**Comment by ViolatorX** [comment]
Not getting the newer 2.3.2.0 and 2.3.3.0 shown on that list though.
Nor does it offer to use already saved dlss files from the subfolders in Documents\DLSS Swapper\dlls

**Comment by beeradmoore** [comment]
As above, dlls are still manually managed via the [dlss-archive](https://github.com/beeradmoore/dlss-archive) repo. There was no rush to get 2.3.2 and 2.3.3 in as they never made it through to the DLSS SDK from NVIDIA so they probably contain fixes for the specific 2 games they exist in. This has now been updated as I finally had free time to do it. Enjoy I guess 🤷‍♂️

I will update the documentation here to make this change clear, and if people really want a new version to go file an issue there.

Documents path was updated as there were multiple reports of peoples computers being unable to access Documents folder. No idea how this is a thing, but app data path should resolve that issue. So move was made to change where they were stored and existing records were migrated.

The path isn't intended to be user friendly, DLSS Swapper intended to have an import feature on the downloads page (and downloads to be renamed to library) but it didn't make the cut and people were pushing for an update to fix a bunch of other issues.

> Really?
> That is not the most user friendly path.

I guess I'll get right on that 🙄

**Comment by ViolatorX** [comment]
Thank you for adding the new DLSS files 2.3.2 as example is better in some games where 2.2.6 was the previously best.
Going to make a spreadsheet for DLSS ratings pr. game on Guru3D, guess it could be nice if those who test them trough rate them so a recommended best DLSS can be estimated.
Will go into the thinker a bit to find a good way on how to do it, since there are a few factors that apply.

With the documents path my my main concern was not being able to inject old and new DLSS libraries via DLSS Swapper  that aren't in the dlss-archive, something that is pretty easy if the folders only contain the version string, not sure if "_7BBBB70F34FC4F2977BA442EE5FC37AC" can be added after those to add some manually?

Cheers

**Comment by beeradmoore** [comment]
In the next update that I was working on today you won't need to care about folder structures. From the downloads screen (soon to be library) you have a menu option to import which will let you browse for a DLL to bring into the system.

**Comment by beeradmoore** [comment]
(Notification for you because I edited the post after you read it)

**Comment by ViolatorX** [comment]
Think such a voting/recommendation system needs to be limited to the geeks that test them throughout.
Currently setting up spreadsheets for some DLSS 2  games  and will see what they think of it.
There is quite some work in making recommendations, as there are multiple factors to consider, so would be a bad idea to leave it to the average gamer.
https://docs.google.com/spreadsheets/d/11k1PPbubZr2Jltcx0FnqEg7QLiJkU6z8nO-MQYRHzU8/edit?usp=sharing

**Comment by ViolatorX** [comment]
Created a page with 17 games that support the DLSS 2.0 libraries, only Back 4 Blood is complete for now, rest will follow, got the forms created for all libraries and their presets, more games will get added in time.
Rating a library preset does require a Google login.
https://sites.google.com/view/dlss2ratings/home

Didn't get around to get the average value for each games preset sheet column to the main sheet yet.

**Comment by beeradmoore** [comment]
Closing this issue because `Unable to update DLSS record` is fixing in 0.9.6.

To help this stay on topic, @ViolatorX  if you wanted to keep investigating or rolling with the discussion of a voting system or how it could work can you create a new issue for that.
