### ISSUE TITLE
no exe file

### ISSUE THREAD

**Issue by DaemonKisure** [beeradmoore/dlss-swapper#6]
the pack doesnt have .exe file and i dont know what to do, there is a tutorial somewhere?

**Comment by beeradmoore** [comment]
Installer will be in the releases tab at some point when I can get that functioning properly.

**Comment by beeradmoore** [comment]
Sorry, the how to use will be populated [here](https://beeradmoore.github.io/dlss-swapper/usage/). 
Still working towards getting installer up, but initial install instructions can be found [here](https://beeradmoore.github.io/dlss-swapper/install/).
