### ISSUE TITLE
[Bug] Add setting for multiple game library paths

### ISSUE THREAD

**Issue by matthewlilly** [beeradmoore/dlss-swapper#61]
**Is your feature request related to a problem? Please describe.**
Only games on C: drive seem to be showing at the moment.

**Describe the solution you'd like**
It would be good to have a setting to select multiple paths to search for games - I have games spread over 3 separate drives.

**Comment by beeradmoore** [comment]
Hey @matthewlilly , DLSS Swapper does scan for games on other drives. But something else may be bugged here and that's why it isn't working.

Are you using the latest version of DLSS Swapper? An easy way to check is to see if the downloads page is still called downloads or if it's called library now.

**Comment by matthewlilly** [comment]
Yeah, using the latest v0.9.6

Does it search for specific folder names? 
My folders are default within drive C:, then like the following for drives D: and E:


```
|-- <drive letter>:
|   |-- Game Library
|       |-- <multiple folders for non-steam games
|       |-- steamapps
|           |-- common
|               |-- <multiple folders for steam games>

```

**Comment by beeradmoore** [comment]
It gets the Steam install directory from your system registry. From your Steam install directory it reads a manifest file (can't link to what one it is because I'm on mobile but I will later) which contains information on your Steam libraries are on external drives.

Each of these Steam libraries have another manifest file which details the games installed to that library path and that's where we read the game info/directories from.

**Comment by beeradmoore** [comment]
At PC so I can send more info.

We load `{SteamInstallPath}/steamapps/libraryfolders.vdf` and get external libraries from that. It's very possible (and has happened in the past) that the way the file is formatted is now different to what we expect.

Ideally if you could get a copy of that file to me I can see if its breaking here or when we read files. I don't believe there is any personally identifiable or private info in the file. That being said are you comfortable to attach the file below? If you want to keep it somewhat private you could upload it as an unlisted [pastebin](https://pastebin.com/) and then email/[DM](https://twitter.com/beeradmoore) me on Twitter.

**Comment by matthewlilly** [comment]
The problem of steam games on a different drive not showing was due to the developers rolling back an update, which added DLSS to the game (Rise of the Tomb Raider) -  installing the latest beta causes it to show up in dlss swapper, as intended.
But I have a few games from Epic and Rockstar which aren't showing, so I'm guessing the the tool is for steam library games only?

I've attached the content of the libraryfolders.vdf anyway, just in case.

```
"libraryfolders"
{
	"contentstatsid"		"<removed-to-share>"
	"0"
	{
		"path"		"C:\\Program Files (x86)\\Steam"
		"label"		""
		"contentid"		"<removed-to-share>"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"12650380311"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"228980"		"208610968"
			"271590"		"108826526069"
			"690790"		"117594033997"
		}
	}
	"1"
	{
		"path"		"D:\\GameLibrary"
		"label"		""
		"contentid"		"<removed-to-share>"
		"totalsize"		"500090007552"
		"update_clean_bytes_tally"		"9632724291"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"203160"		"11733553195"
			"292030"		"53483389454"
			"379720"		"73756206574"
			"391220"		"26753139004"
			"750920"		"37928623584"
		}
	}
	"2"
	{
		"path"		"E:\\GameLibrary"
		"label"		"Storage"
		"contentid"		"<removed-to-share>"
		"totalsize"		"500090007552"
		"update_clean_bytes_tally"		"2470060026"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"12200"		"5337963430"
			"35000"		"6229905310"
			"35140"		"8471095333"
			"200260"		"19948606783"
			"205100"		"14014816283"
			"212480"		"7688584411"
			"213670"		"5723685400"
			"261570"		"7934653406"
			"403640"		"45265330837"
			"418240"		"7817019172"
			"610370"		"23456706999"
			"614570"		"25489409283"
			"731490"		"31201744091"
			"860950"		"8096184287"
			"996580"		"41603544369"
			"1057090"		"12149438740"
		}
	}
	"3"
	{
		"path"		"R:\\GameLibrary"
		"label"		"Retro"
		"contentid"		"<removed-to-share>"
		"totalsize"		"240038965248"
		"update_clean_bytes_tally"		"2233593573"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"362890"		"30064617865"
			"367520"		"7972875944"
			"435400"		"299983456"
			"501300"		"2540778487"
			"632360"		"3358597362"
			"1062160"		"443065508"
			"1127500"		"193069216"
		}
	}
}

```

**Comment by beeradmoore** [comment]
Ohh I may have overlooked something. In DLSS Swapper, in the top right there is a filter button. If you hit that and then untick "hide non-dlls games" do games on all your external drives show up?

I ran your libraryfolders.vdf and it pulled the paths out as expected.

At the moment it only fetches Steam games. I was looking more into Ubisoft Connect earlier today, that platform will be next. If you want to keep track of when they are done you can go to the issues section and look for the related filed issue (eg. #13 for rockstar social club) and hit subscribe under notifications on the right.

**Comment by matthewlilly** [comment]
Yeah, the filter actions work as intended.

I'll just copy across the downloaded .dll files to non-steam for now, and subscribe to other issues.
