### ISSUE TITLE
[Feature request] Add Xbox App Game library 

### ISSUE THREAD

**Issue by adenlim** [beeradmoore/dlss-swapper#63]
If it is possible to manually add games from the Xbox App for Windows into DLSS swapper

**Comment by beeradmoore** [comment]
With the old Xbox app and installing games into the WinApps folder this can't happen.

With the new preview Xbox app where it can install into any directory this may be possible. I'm still waiting for the preview to become available for me to look at if this is possible then.

**Comment by beeradmoore** [comment]
Closing in favor of tracking this in #2
