### ISSUE TITLE
Installation failed, error 0x8000FFFF [BUG] 

### ISSUE THREAD

**Issue by Rh0d1um** [beeradmoore/dlss-swapper#65]
A few months (still running Windows 10 back then) ago I already installed an early version of DLSS Swapper. Since then I upgraded to Windows 11 and wanted to start DLSS Swapper again. I had trouble downloading newer DLSS version from within the app, so I wanted to update the app (not knowing, that it would do that on its own). Then I uninstalled the app and wanted to reinstall with 0.9.6.0. I got greeted by the error message No. 1 below. I tried installing the dependencies manually, but that would fail too, with error message No. 2. I also tried reinstalling the certificate, but that didn't help either. Is there anything I could do on my side to fix this issue? Thanks!

ERROR No 1: "App installation failed with error message: Deployment Add operation with target volume C: on Package cc5a0fee-f182-4d02-a177-3c2f002b4f34_0.9.6.0_neutral_~_vn8kspbc310ge from:  (bundle-x64.msixbundle)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)"

ERROR No 2: "App installation failed with error message: Deployment of package Microsoft.ProjectReunion.0.8_8005.278.2204.0_x64__8wekyb3d8bbwe was blocked because the provided package has the same identity as an already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every user on the system before installing this package. (0x80073cfb)"

**Comment by beeradmoore** [comment]
Hey @Rh0d1um , sorry you are having issues with it. 

I'd try re-install the certificate again (instructions [here](http://beeradmoore.github.io/dlss-swapper/install/)) and then try re-install via the [download page](https://beeradmoore.github.io/dlss-swapper/download/).

If that fails I'd uninstall the previously installed dependencies (they are on the [releases tab](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.6.0) prefixed with name dependencies) and then install from the download page again.

Let me know how that goes.

**Comment by Rh0d1um** [comment]
Weird, I tried reinstalling the certificate again, and now I could install without any problem and the swapper works fine! I'm almost 100% sure that I reinstalled the certificate exactly the same an hour ago -- oh well, as long as everything works ;-)

Thanks for the quick help! I appreciate it a lot.

**Comment by beeradmoore** [comment]
Glad its all sorted.
