### ISSUE TITLE
[BUG] The ms-appinstaller Protocol has been Disabled

### ISSUE THREAD

**Issue by Zarraya** [beeradmoore/dlss-swapper#69]
**Describe the bug**
Due to a security vulnerability, the ms-appinstaller protocol has been disabled. This is preventing me from following the guide and installing the version from the website. I was able to install via downloading the files from GitHub directly and installing from there. There are apparently work arounds until Microsoft fixes the issue.

**Comment by beeradmoore** [comment]
Hey @Zarraya , was this disabled on your system or remotely on a large scale by MS?

This should be a non issue when I publish to the Windows store.

**Comment by Zarraya** [comment]
It appears to be remotely on a large scale by Microsoft.

**Comment by beeradmoore** [comment]
That's fun.

I'll push up timeline of getting published to the store and updating install instructions to point to that. Cheers for pointing this out.

**Comment by XanderXAJ** [comment]
Just to confirm that this is large-scale by Microsoft -- see the box labelled important at the top of this page:
https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web

The workaround to install is that you can use the `.appinstaller` or the `.msixbundle` from the releases page:
https://github.com/beeradmoore/dlss-swapper/releases

**Comment by mattmogford** [comment]
> Just to confirm that this is large-scale by Microsoft -- see the box labelled important at the top of this page: https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web
> 
> As a workaround, to install you can use the `.appinstaller` or the `.msixbundle` from the releases page: https://github.com/beeradmoore/dlss-swapper/releases

As a brand new user, this is the only way for me to get the app.
@beeradmoore could add a quick 1 liner to the readme/install instructions to mention this for now?
e.g. download straight from github releases instead of clicking the link.

**Comment by beeradmoore** [comment]
Install instructions should be more clear now. Can you let me know how I went?

[https://beeradmoore.github.io/dlss-swapper/install/](https://beeradmoore.github.io/dlss-swapper/install/)

**Comment by mattmogford-alcumus** [comment]
Looks good.
I just wanted to make sure other people didn't go down a dead end like me :)
Great app btw!

**Comment by beeradmoore** [comment]
Writing code is easy. Making sure it makes sense to other devs and all the supporting documents for the end users exists and works is the difficult bit 😂
