### ISSUE TITLE
[Feature request] Support for Adding Custom Games to Library

### ISSUE THREAD

**Issue by DashCruft** [beeradmoore/dlss-swapper#70]
Hello!

One thing lacking in this software is the feature of adding custom games to the library of it. 
This will save alot of time, and it's much better in case of not wanting to create detection for each launcher other then steam!

It can also speed up people's swapping and they wont have to download it each time and extract it

**Comment by beeradmoore** [comment]
Hey @DashCruft , thanks for the feature request. We are already tracking this in issue #8 (will close this to track in that already existing issue). 

I agree it would get other platforms into the system sooner but I wouldn't say it's easier as there is a lot of unknowns: 
- How does the UI work for user to enter the game name, or do we just use the directory name to be displayed in app?
- What icon do we display in the app?
- What do we do to inform the user if the folder no longer exists, should we remove it like auto-scan would or should we prompt them that the folder is no longer accessible and would they like to point it at a new folder?
- What do we do if someone manually added a game that was auto-scanned?
(etc etc, probably other things not thought of as well that we would find during development)

On the plus side Ubisoft Connect work (in local repo I have here) is mostly done, and I had been in small talks with some people for getting support in Windows Store games with the new advanced install system they have.
