### ISSUE TITLE
Github Readme file, Microsoft store link broken.

### ISSUE THREAD

**Issue by m4gnify** [beeradmoore/dlss-swapper#76]
The link to the Microsoft Store is broken.
screenshot:
![firefox_5fB8DP5OlE](https://user-images.githubusercontent.com/8404962/157739015-3e9dcd06-1ef5-4cbc-86a7-8b7851c5663c.jpg)

Clicking it brings you to a "the page you requested cannot be found".

I guess it should be like this.

Now: "[https://www.microsoft.com/store/apps/9NNL4H1PTJBL](Microsoft Store)"

Should be: "[Microsoft Store](https://www.microsoft.com/store/apps/9NNL4H1PTJBL)" 
`[Microsoft Store](https://www.microsoft.com/store/apps/9NNL4H1PTJBL)`

**Comment by beeradmoore** [comment]
Whops 😅

Fixed now. Thanks for pointing that out.
