### ISSUE TITLE
[Feature request] Add/Remove Games Manually.

### ISSUE THREAD

**Issue by Wontell** [beeradmoore/dlss-swapper#77]
Please add an option to manually add games, since many games are not shown.
Also allow us to remove added games.
If adding games manually not possible then add an option to add paths for were to look for games.

Regards

**Comment by Wontell** [comment]
For example: I have Death Stranding Directors Cut from Epic and its not showing

**Comment by beeradmoore** [comment]
Hey, thanks for filing the issue.

Epic Games Store is being tracked in issue #11 
Manually adding games is being tracked in issue #8 

Closing this issue in favour of the, but please go give those a 👍 so I can help prioritise work based on user desire.
