### ISSUE TITLE
Unable to load dlss_records.json

### ISSUE THREAD

**Issue by RicLPereira** [beeradmoore/dlss-swapper#84]
I keep getting an error when installing. Both from the microsoft store and with a manual install. Certificate installs properly,  but then the actual app install keeps giving the same error. "We were unable to load dlss_records.json from your computer or from the internet"

**Comment by beeradmoore** [comment]
Hey RicLPereira 
This sounds like there is an issue either downloading or saving the initial list of DLSS records that exist for some reason.

If you go to https://raw.githubusercontent.com/beeradmoore/dlss-archive/main/dlss_records.json does it load a list of items for you?

**Comment by RicLPereira** [comment]
> 

Yes it does. It shows me all the different versions of DLSS

**Comment by RicLPereira** [comment]
This is the exact message that pops up
![Screenshot 2022-09-08 194456](https://user-images.githubusercontent.com/112976460/189244504-ad803322-49b6-411c-9181-280e66d7eab5.png)

**Comment by beeradmoore** [comment]
On the weekend I can do a more diagnostic build to try bubble up the underlying issue for you, like put an error code in there so we can see where it is dying.

There are multiple things that happen in this flow. It first downloads that file I sent you, then it saves it into a specific windows package folder (so we don't have to download it again next time), then it will try read it and load each of those lines into things the code uses. It is possible for any part in there to fail which would present this issue to you.

You can either wait for that or we can attempt another step. If you uninstall the app to ensure neither Windows Store or GitHub releases are installed, then install a fresh copy from Windows Store, then open it so you get the error. After that we can see if it downloaded the above file and saved it correctly. If you go to `C:\Users\<your user name>\AppData\Local\Packages\` (assuming C drive is where your users folder is) and sort the folder by date modified then DLSS Swappers data folder should be up the top. I am not 100% sure what its name will be but for me it is `55588beeradmoore.DLSSSwapper_xkmn.......`.

If you go into that folder and then into `LocalState` there should be a `dlss_records.json` file in there. In theory if you open that (notepad should be fine if you don't have other tools installed) it should look like the file I linked you in the previous comment. So long as the top looks the same, and bottom looks the same, we can assume the entire file is the same.

If the file (or any of the folders) don't exist we may have an issue trying to save this file correctly and that is why we are getting issues.

**Comment by RicLPereira** [comment]
When I go into that folder, it is completely empty. It disappears when I uninstall it, but after installing it, the folder stays empty

**Comment by beeradmoore** [comment]
Just to confirm, it is empty while DLSS Swapper is running and it gives you the error you posted above? (the folder should be empty until it downloads the file while running)

What happens if you put the a file named dlss_records.json which you download from https://raw.githubusercontent.com/beeradmoore/dlss-archive/main/dlss_records.json into that folder then run DLSS Swapper?

Concerned there are some write permission issues happening here. Is your account a limited user account by any chance or is it full admin?

**Comment by RicLPereira** [comment]
Yes the folder stays empty even while DLSS Swapper is running. Seems like putting in a file called dlss_records.json with the contents you sent fixed it though. It launches properly now. Not sure why it wasn't automatically placing a file there like it was supposed to though. I couldn't seem to find anyone else having that problem

**Comment by beeradmoore** [comment]
Mmm.. this is odd. 

Now that we know what a temp fix is do you mind if I put up a custom build over the new few days for you to install via GitHub, and to delete that file from the folder so we can get it to output a better error or what is happening. Concern here is it is "working" but unsure if you will run into issues with downloading DLSS files, updating the main dlss_records.json list in the future, saving game cover images into our own cache (future update).

**Comment by RicLPereira** [comment]
Ya sure I don't mind. Just let me know when the build is ready and I'll try it out

**Comment by beeradmoore** [comment]
Took a few extra days but I have some things. I appreciate the assistance from your end.

If you could first uninstall DLSS Swapper.
There is a new certificate file ([dlss-swapper.cer](https://github.com/beeradmoore/dlss-swapper/releases/download/v0.9.10.0/dlss-swapper.cer)) to install, there should be no need to remove the old certificate. If there are issues installing it maybe you did need to remove it (I didn't know this certificate had expired which is why there is a new one). You mentioned you had already done it earlier, but if you need the instructions on how to install are [here](https://beeradmoore.github.io/dlss-swapper/install/).
After that you can get the new installer [DLSS-Swapper-Preview.appinstaller](https://github.com/beeradmoore/dlss-swapper/releases/download/v0.9.10.0/DLSS-Swapper-Preview.appinstaller) from the pre-release page [here](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.10.0).

There is a new option for logging items in settings. For this build it is set to verbose by default so you should not need to change it. If you go into the app Settings it should also show you how to access this log.

The error message you were getting above will not be any different but hopefully we get some info as to what is wrong in that log file.

If everything works fine maaaybe it was that the certificate had expired >_>

**Comment by beeradmoore** [comment]
That is really weird.
The urls it is trying to get are https://api.github.com/repos/beeradmoore/dlss-swapper/releases/latest and https://raw.githubusercontent.com/beeradmoore/dlss-archive/main/dlss_records.json I that we mentioned before.

Both I am pretty sure you can access in your browser just fine.

Do you have any firewall programs that could be blocking access for apps accessing the internet, or maybe is your computer setup to be going through a proxy or VPN and DLSS Swapper is not handling that correctly?

Are you able to use the tool to download a DLSS record? It should be trying to download from a URL like https://github.com/beeradmoore/dlss-archive/releases/download/v2.4.12.0/nvngx_dlss_2.4.12.0.zip. But if the first two are blocked somehow I expect this to also not work, and if this one does work within DLSS Swapper it just makes everything even more confusing 😂

**Comment by RicLPereira** [comment]
No I don't have anything like that. Was connected to a vpn before but not anymore. Doesn't work either way. For firewall or antivirus that could be blocking anything, I just have windows defender which I also turned off just to try. By manually adding the dlss_records.json file I can launch the app, but downloading any version of DLSS crashes the application. This is the logs from me launching and trying to download 2 versions of dlss. Both times it just crashes. I really have no idea why I'm having this issue lol. Can't think of anything that could be causing it
![Screenshot 2022-09-13 221437](https://user-images.githubusercontent.com/112976460/190043353-626b9765-ee9b-4694-be65-06acf2eedd55.png)

**Comment by beeradmoore** [comment]
The crashing makes sense. I'll look into that to make it error and not crash as I expect if people lose internet connectivity they will be in the same boat when they try connect.

I assume other apps are not giving you a bunch of trouble?
Silly question, but have you tried rebooting?

But I am at a loss as to why DLSS Swapper is broken here. We have at least confirmed it's a network issue of some sort and not a file permission issue. But the fact that it works if you put the addresses in a browser is just adding to the confusion.

In theory you can use your manual dlss_records.json trick to get past the first step and then in the library screen you can import DLSS records from your computer which you can download from here, https://github.com/beeradmoore/dlss-archive/releases. That way DLSS Swapper should still be able to help you swap and reset DLSS versions, just won't be able to automatically download new DLSS versions for you.

**Comment by RicLPereira** [comment]
Lol ya I've rebooted as well. No other app is giving me any trouble. Everything else has been working like usual. 0 issues. I have no idea as to why this app doesn't work. I've used it before on an old computer and it worked perfectly back then

**Comment by RicLPereira** [comment]
Hey just wanted to let you know. With the new version you just released (v0.9.12.0), all of my issues are fixed. It installs with no problems and I can now download any DLSS version and swap them with no issues

**Comment by beeradmoore** [comment]
That makes no sense -_-, but glad it is working for you.

I opened a new issue with #92 as investigating this was not giving good results and there is no reason this should not be usable offline.

**Comment by RicLPereira** [comment]
Lol I'm not sure what could have fixed it since nothing changed on my end since last time, but I'm happy it did

**Comment by AkechiiYEETS** [comment]
Still got this issue, though disabling my VPN did fix it.
