### ISSUE TITLE
[BUG] DLSS Swapper crashes on search for games

### ISSUE THREAD

**Issue by jtoya85** [beeradmoore/dlss-swapper#94]
**Describe the bug**
Just updated to 0.9.13 and when the program searches for games installed it crashed within seconds.
**To Reproduce**
1. Update or Reinstall DLSS Swapper, either from Git Hub or MS Store.
2. Launch DLSS Swapper
3. Crash
**Expected behavior**
DLSS Swapper should search for games installed then display them.
**Screenshots**

**Additional context**
Same error in Event Viewer:
Faulting application name: DLSS Swapper.exe, version: 1.0.0.0, time stamp: 0x6331eb0e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2130, time stamp: 0xb0fac6c9
Exception code: 0xc000027b
Fault offset: 0x000000000010fdf2
Faulting process id: 0x2d8
Faulting application start time: 0x01d8e1a0626c76e7
Faulting application path: C:\Program Files\WindowsApps\cc5a0fee-f182-4d02-a177-3c2f002b4f34_0.9.13.0_x64__vn8kspbc310ge\DLSS Swapper\DLSS Swapper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ec7819db-eb40-491d-bd4d-c9a15d31af86
Faulting package full name: cc5a0fee-f182-4d02-a177-3c2f002b4f34_0.9.13.0_x64__vn8kspbc310ge
Faulting package-relative application ID: App

**Comment by beeradmoore** [comment]
Hey @jtoya85 , thanks for the repot. 

First thing I'd like to ask what of the following libraries do you have installed on your system, and of the ones you have what ones do you have games installed with? 
- Steam
- GoG
- Ubisoft Connect
- Epic Games Store
- Xbox App (this may also include games installed directly from the Windows Store)

DLSS now has an error logging feature so hopefully that will have some answers in that file. To access the log you can open an explorer window and in the path of the current directory if you can put in %TEMP% this will take you to your temporary files.

The log files should be dlss_swapper_{date}.log, so if you sort by name you should find the logs grouped together. If they exist are you are able to post those below.

**Comment by jtoya85** [comment]
I have games on Steam, Ubisoft Connect and Epic Games store, as well as Origin/EA App. I've attached the latest log file.

[dlss_swapper_20221016.log](https://github.com/beeradmoore/dlss-swapper/files/9795800/dlss_swapper_20221016.log)

**Comment by beeradmoore** [comment]
Thanks for the quick response. Looks like a bunch of errors regarding Ubisoft Connect.

```
2022-10-16 16:38:27.202 -04:00 [ERR] UbisoftConnectLibrary.cs:203 ListGamesAsync - Error parsing Ubisoft Connect element. (Exception during deserialization)
2022-10-16 16:38:27.203 -04:00 [ERR] UbisoftConnectLibrary.cs:203 ListGamesAsync - Error parsing Ubisoft Connect element. (While scanning a multiline plain scalar, found invalid mapping.)
2022-10-16 16:38:27.203 -04:00 [ERR] UbisoftConnectLibrary.cs:203 ListGamesAsync - Error parsing Ubisoft Connect element. (Did not find expected <document end>.)
2022-10-16 16:38:27.212 -04:00 [ERR] UbisoftConnectLibrary.cs:90 ListGamesAsync - Could not load Ubisoft Connect item.
```

Are you able to double check that Ubisoft Connect is up to date? 
Is Ubisoft Connect set to use English? I am curious if there is a language issue with going over that file if there is unexpected characters.


There is an system I wanted to make so people could toggle off independent game libraries if they don't want to have it bother loading it. Thinking about it now that could fit nicely with crash detection giving you the opportunity to disable one of the game platforms on launch to try reduce the harm of this in future.

**Comment by jtoya85** [comment]
I just updated Ubisoft Connect and double checked that it was using English, neither helped. 
[dlss_swapper_20221016.log](https://github.com/beeradmoore/dlss-swapper/files/9795848/dlss_swapper_20221016.log)

**Comment by beeradmoore** [comment]
Thanks for double checking that. 

The next option would either wait for me to add the thing I mentioned above and we disable Ubisoft Connect, or if you could send me a copy of the file that is having issues being read. I believe this file contains a list of all game entries either that Ubisoft Connect has, or of what what your account has on Ubisoft Connect. I don't believe there is any personally identifying information, or any security data the file.

If you wanted to send the file, its default location is `C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations`, but this will vary on if you installed Ubisoft Connect elsewhere. If you didn't want to post it publicly we can arrange email/filedrop/DM, etc.

Once I have that file I can point my installer at it and step through and see why it complains about it.

**Comment by jtoya85** [comment]
[configurations.zip](https://github.com/beeradmoore/dlss-swapper/files/9795914/configurations.zip)

**Comment by beeradmoore** [comment]
Cheers. Looking at it visually I can't see anything out of the ordinary. I will look into it deeper tonight (~8hours in my timezone) and let you know how I go.

**Comment by beeradmoore** [comment]
Hey @jtoya85 , I was able to look into that configuration file I can see how I am reading it wrong. I am unsure if that is causing the crashing or not though. So I was not able to fix that just yet.

I did however make a pre-release of [v0.9.14.0](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.14.0) which can _hopefully_ detect a crash and on re-launch will prompt you to disable individual game libraries. If it doesn't then the crash is elsewhere and I will have to look into it more tomorrow.

If you get time to install this version and give it a go it would be greatly appreciated. Thanks!

**Comment by beeradmoore** [comment]
I may have to add an actual full crash logger that can capture the crashes. I may have pre-emptively jumped at Ubisoft Connect as being the culprit because it is broken in different ways but seemingly not responsible for the crashes.

Just to clarify, if you have only Steam enabled it crashes? If you have only Epic Games Store enabled it crashes? Would you be able to disable all and go through them and just have 1 enabled at a time?

**Comment by jtoya85** [comment]
Steam, alone, works fine.
GOG works fine.
Epic Games causes a crash but no log file.
Ubisoft works fine.
XBox App works fine.
I just noticed that this was made right now.
[dlss_swapper_20221017.log](https://github.com/beeradmoore/dlss-swapper/files/9805058/dlss_swapper_20221017.log)

**Comment by beeradmoore** [comment]
Thanks for testing that. I will focus on Epic Games Store and see what I can find.

Is there anything specific you can think of about your Epic Games Store install that could be possibly different to my setup. Running in English? Installed to default drive? Is it updated? Games installed across multiple drives? Are other libraries/accounts linked directly in EGS?, etc.

**Comment by jtoya85** [comment]
All but one of my games through Epic are on the same drive, its a 5400 RPM 4tb HDD if that matters, while the Epic launcher files are on my main boot drive(so Epic is spread between 3 drives). Epic is only manual updates to the launcher so idk if that has anything to do with the crash, though I just opened it and there was no update required. Language is set to English. I don't link any accounts to Epic.

**Comment by beeradmoore** [comment]
Aighty. I'll dig deeper into Epic Games Store for 0.9.15.0 release. If I don't find the problem Ill at least add more logging so we can get to the bottom of that.

If you are able to collect, zip, and send these files like you did with Ubisoft Connect ones that could prove to be very useful.

This is where they are located on my PC.
```
C:\ProgramData\Epic\EpicGamesLauncher\Data\Catalog\catcache.bin
C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests\*.item
```
Inside the Manifest folder there are a bunch of files with a long line of numbers and letters. I think aside from another folder they are the only thing inside the Manifests folder.

**Comment by jtoya85** [comment]
[catcache.zip](https://github.com/beeradmoore/dlss-swapper/files/9805306/catcache.zip)
That has the catcache.bin and all the .item files that were in those folders.

**Comment by beeradmoore** [comment]
Cheers. Will jump into these tonight and let you know if I find anything.

**Comment by beeradmoore** [comment]
Thanks for those files @jtoya85. When I pointed my dev build at them it crashed and I saw what was wrong in 1 second. Took 1 more second to fix it -_- 

v0.9.15.0 is on its way soon.

**Comment by beeradmoore** [comment]
Update, v0.9.15.0 has been [released](https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.15.0). 

Thanks again for your quick responses and sample files to help get this resolved.
