### ISSUE TITLE
[BUG] App removed from Microsoft Store? 

### ISSUE THREAD

**Issue by Chattermouth** [beeradmoore/dlss-swapper#96]
The App cannot be found on Microsoft Store.

The link on your install page leads to a github 404 (https://beeradmoore.github.io/dlss-swapper/Microsoft%20Store).

Copypasting the link text (https://www.microsoft.com/store/apps/9NNL4H1PTJBL) leads to a "We are sorry, the page you requested cannot be found." page at Microsoft.

Cannot even find the app in the store by searching for DLSS.

**Comment by beeradmoore** [comment]
Known issue, one I'm currently trying to make a workaround for.

MS review process apparently didn't pick it up in the past but there is a rule against apps that download external binaries 🤷‍♂️

Working on a new and improved system. WindowsStore app will contain all known DLSS versions. GitHub version will no longer need certificate installation, it will be just a regular installer. Plus it may also be released as a portable version so you just extract a zip and that's your app.

**Comment by beeradmoore** [comment]
I have made my required changes, but there is no way to actually submit them. The Microsoft Store backend is the worst store backend I have used. It is no longer worth putting in the effort to support this build of the app.

But now that we have installable DLSS Swapper that does not have other dependencies or certificates I am pulling DLSS Swapper from the store for good.
