### ISSUE TITLE
[BUG] This app package’s publisher certificate could not be verified - how can i fix this

### ISSUE THREAD

**Issue by Crimsxn09** [beeradmoore/dlss-swapper#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Full error from original title: Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

**Comment by beeradmoore** [comment]
There is a new certificate as the old one expired. You can find the new one on the latest release, https://github.com/beeradmoore/dlss-swapper/releases/tag/v0.9.15.0

Does that resolve the problem?

**Comment by beeradmoore** [comment]
Any update on this from your side @Crimsxn09 ?

**Comment by JasonHiew** [comment]
It worked after using the .cer file included in the latest release. Thanks.

You should update the signing certificate on your manual installation guide. The one there has expired
![image](https://user-images.githubusercontent.com/24473087/208593669-e7d1893c-b2fa-4f4e-8987-b02811b5b58e.png)

**Comment by beeradmoore** [comment]
Thanks for pointing that out @JasonHiew, I've updated that now.

Next release won't have any certificate stuff to deal with so that's a huge plus so people don't have to jump through hoops.
